(function(){
  const baseRenderApp=window.renderApp,baseRenderContent=window.renderContent;
  function isAdmin(){const can=(state.boot&&state.boot.can)||{};return !!can['admin.people'];}
  window.renderApp=function(){baseRenderApp();if(isAdmin()){const nav=document.querySelector('.tabs');if(nav&&!document.getElementById('adminUsersTab')){const b=document.createElement('button');b.id='adminUsersTab';b.textContent='Quản trị';b.className=state.tab==='adminUsers'?'active':'';b.onclick=()=>{state.tab='adminUsers';renderApp();};nav.appendChild(b);}}};
  window.renderContent=function(){if(state.tab==='adminUsers'&&isAdmin())return renderAdminUsers();return baseRenderContent();};
  async function renderAdminUsers(){const host=document.getElementById('content');host.innerHTML='<div class="empty">Đang tải quản trị…</div>';try{const [users,docs]=await Promise.all([call('salesAdmin','listUsers',{}),call('documents','list',{})]);paint(users||[],(docs||[]).filter(d=>String(d.status)==='PENDING_APPROVAL'));}catch(e){host.innerHTML='<div class="empty">'+esc(e.message)+'</div>';}}
  function paint(users,pending){const host=document.getElementById('content');host.innerHTML=`<section class="hero compact-hero"><div><h1>Quản trị Sunbot Ops</h1><p>Người dùng, PIN và các Proposal đang chờ quyết định.</p></div><button class="btn" id="newUserBtn">＋ Thêm user</button></section>${pending.length?`<section class="approval-queue"><div class="section-head"><div><span class="role-label">CẦN DUYỆT</span><h2>${pending.length} Proposal đang chờ</h2></div></div>${pending.map(approvalRow).join('')}</section>`:''}<section class="section-head admin-users-head"><div><span class="role-label">NGƯỜI DÙNG</span><h2>Tài khoản & phân quyền</h2></div></section><section class="admin-user-grid">${users.map(userCard).join('')}</section><section class="admin-note"><b>Backend đồng bộ:</b> tab <code>AUTH_CREDENTIALS</code> cho phép Admin xem/sửa <code>login_id</code> và <code>visible_pin</code>. PIN chỉnh trực tiếp trong backend sẽ được đồng bộ verifier khi user đăng nhập.</section>`;
    document.getElementById('newUserBtn').onclick=()=>openEditor(null);document.querySelectorAll('[data-user-edit]').forEach(b=>b.onclick=()=>openEditor(users.find(x=>x.user_id===b.dataset.userEdit)));document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>resetPin(b.dataset.reset));document.querySelectorAll('[data-active]').forEach(b=>b.onclick=()=>toggleActive(b.dataset.active,b.dataset.value==='true'));document.querySelectorAll('[data-approve-doc]').forEach(b=>b.onclick=()=>approveDoc(b.dataset.approveDoc));document.querySelectorAll('[data-reject-doc]').forEach(b=>b.onclick=()=>rejectDoc(b.dataset.rejectDoc));}
  function approvalRow(d){return `<article class="approval-row"><div><b>${esc(d.reference||'Proposal')}</b><span>${esc(d.outreach_id||'')}</span><small>Tạo bởi ${esc(d.created_by_user_id||'')} · ${esc(d.created_at||'')}</small></div><div class="document-links">${d.doc_url?`<a class="btn ghost" href="${esc(d.doc_url)}" target="_blank" rel="noopener">Xem dự thảo</a>`:''}${d.pdf_url?`<a class="btn ghost" href="${esc(d.pdf_url)}" target="_blank" rel="noopener">PDF nháp</a>`:''}<button class="btn secondary" data-approve-doc="${esc(d.document_id)}">Duyệt</button><button class="btn ghost" data-reject-doc="${esc(d.document_id)}">Trả lại</button></div></article>`;}
  function userCard(u){return `<article class="admin-user-card"><div><span class="role-label">${esc(u.role_class||'OTHER')}</span><h3>${esc(u.ho_ten||u.user_id)}</h3><p><b>ID:</b> ${esc(u.login_id||u.user_id)} · <b>PIN:</b> <span class="pin-text">${esc(u.visible_pin||'—')}</span></p><small>${esc(u.email||'Không yêu cầu email')} · ${esc(u.dia_ban||'Chưa gán địa bàn')}</small></div><div class="admin-user-actions"><button class="btn secondary" data-user-edit="${esc(u.user_id)}">Sửa</button><button class="btn ghost" data-reset="${esc(u.user_id)}">Reset PIN</button><button class="btn ghost" data-active="${esc(u.user_id)}" data-value="${String(u.trang_thai).toUpperCase()==='ACTIVE'?'false':'true'}">${String(u.trang_thai).toUpperCase()==='ACTIVE'?'Khóa':'Mở'}</button></div></article>`;}
  function modalHost(){let x=document.getElementById('adminModal');if(!x){x=document.createElement('div');x.id='adminModal';x.className='workspace-overlay';document.body.appendChild(x);}return x;}
  function openEditor(u){const x=modalHost();x.classList.add('open');const isNew=!u;x.innerHTML=`<div class="workspace-panel add-school-panel"><header class="workspace-head"><div><h2>${isNew?'Thêm user':'Sửa user'}</h2><p>Leader quản lý trường và có thể giao cho Staff. Staff chỉ làm trên trường được giao.</p></div><button class="workspace-close" id="admClose">×</button></header><div class="add-school-form"><label>Họ tên<input id="admName" class="input" value="${esc(u?.ho_ten||'')}"></label><div class="form-grid"><label>ID đăng nhập<input id="admLogin" class="input" value="${esc(u?.login_id||'')}"></label><label>Vai trò<select id="admRole" class="input"><option value="LEADER" ${u?.role_class==='LEADER'?'selected':''}>Leader</option><option value="STAFF" ${!u||u.role_class==='STAFF'?'selected':''}>Staff</option></select></label></div><div class="form-grid"><label>Email (không bắt buộc)<input id="admEmail" class="input" value="${esc(u?.email||'')}"></label><label>Địa bàn<input id="admArea" class="input" value="${esc(u?.dia_ban||'')}"></label></div>${isNew?'<label>PIN 6 số<input id="admPin" class="input" inputmode="numeric" maxlength="6" placeholder="Nhập PIN khởi tạo"></label>':''}<button class="btn full" id="admSave">Lưu người dùng</button></div></div>`;document.getElementById('admClose').onclick=()=>x.classList.remove('open');document.getElementById('admSave').onclick=async()=>{try{await call('salesAdmin','saveUser',{user_id:u?.user_id||'',ho_ten:document.getElementById('admName').value,login_id:document.getElementById('admLogin').value,role_class:document.getElementById('admRole').value,email:document.getElementById('admEmail').value,dia_ban:document.getElementById('admArea').value,pin:isNew?document.getElementById('admPin').value:''});x.classList.remove('open');toast('Đã lưu user.');renderAdminUsers();}catch(e){toast(e.message,true);}};}
  async function resetPin(id){const pin=prompt('Nhập PIN mới 6 số');if(pin===null)return;try{await call('salesAdmin','resetPin',{user_id:id,new_pin:pin});toast('Đã reset PIN.');renderAdminUsers();}catch(e){toast(e.message,true);}}
  async function toggleActive(id,active){if(!confirm(active?'Mở lại user này?':'Khóa user này?'))return;try{await call('salesAdmin','setActive',{user_id:id,active});toast('Đã cập nhật user.');renderAdminUsers();}catch(e){toast(e.message,true);}}
  async function approveDoc(id){try{const r=await call('documents','approve',{document_id:id});toast(r.message||'Đã duyệt Proposal.');renderAdminUsers();}catch(e){toast(e.message,true);}}
  async function rejectDoc(id){const note=prompt('Nội dung cần chỉnh sửa');if(note===null)return;try{await call('documents','reject',{document_id:id,note});toast('Đã trả lại Proposal.');renderAdminUsers();}catch(e){toast(e.message,true);}}
})();