const LIVE=window.SUNBOT_LIVE_DATA||null;
const DATA=LIVE&&LIVE.profiles?LIVE.profiles:{};
const TEAM=LIVE&&LIVE.team?LIVE.team:[];
const TASKS=LIVE&&LIVE.tasks?LIVE.tasks:[];
const META=LIVE&&LIVE.meta?LIVE.meta:{};
let state={role:'ceo',page:'overview'};
function visibleTasks(){if(state.role==='ceo')return TASKS;const id={dung:'TCH-LTD-012',thu:'TCH-NTA-014',nhung:'UP-HOANG-NHUNG'}[state.role];return TASKS.filter(t=>t[6]===id)}
function nav(){return [['overview','⌂','Tổng quan'],['team','◎','Đội ngũ'],['tasks','✓','Công việc'],['accounts','▣','Trường & đơn vị'],['finance','₫','Công nợ'],['reports','▤','Báo cáo tuần'],['ai','✦','AI Feed']].map(x=>`<button data-page="${x[0]}" class="${state.page===x[0]?'active':''}">${x[1]} <span>${x[2]}</span></button>`).join('')}
function kpis(d){return `<div class="kpis">${(d.kpis||[]).map((k,i)=>`<div class="card kpi ${i===0?'accent':''}"><div class="label">${k[0]}</div><div class="value">${k[1]}</div><div class="hint">${k[2]}</div></div>`).join('')}</div>`}
function attention(d){const list=d.attention||[];return `<div class="card section"><h2>${state.role==='ceo'?'CEO Attention':'Việc cần chú ý'}</h2><div class="attention">${list.length?list.map(a=>`<div class="attention-item"><span class="dot ${a[0]}"></span><div><b>${a[1]}</b><small>${a[2]}</small></div><span class="deadline">${a[3]}</span></div>`).join(''):'<div class="empty">Hiện chưa có điểm nghẽn cần xử lý.</div>'}</div></div>`}
function teamCards(){return `<div class="team">${TEAM.map(p=>`<div class="person" data-role-card="${p.key}"><div class="avatar">${p.name.split(' ').slice(-1)[0].slice(0,1)}</div><h3>${p.name}</h3><p>${p.role}<br>${p.area}</p><div class="meta"><span class="mini">${p.id}</span><span class="mini">${p.open} việc mở</span></div></div>`).join('')}</div>`}
function taskTable(){const rows=visibleTasks();return `<div class="card section"><h2>Công việc ưu tiên</h2><div class="table-wrap"><table class="table"><thead><tr><th>Ưu tiên</th><th>Công việc</th><th>Owner</th><th>Trạng thái</th><th>Hạn</th><th>CEO</th></tr></thead><tbody>${rows.map(t=>`<tr><td class="priority">P${t[0]}</td><td><b>${t[1]}</b>${t[7]?`<br><small style="color:var(--muted)">${t[7]}</small>`:''}</td><td>${t[2]}</td><td><span class="tag ${String(t[3]).toLowerCase()}">${t[3]}</span></td><td>${t[4]}</td><td>${t[5]==='Có'?'<span class="tag ceo">Cần CEO</span>':'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Chưa có công việc.</td></tr>'}</tbody></table></div></div>`}
function overview(d){return `${kpis(d)}<div class="grid2">${attention(d)}<div class="card section"><h2>Đội ngũ vận hành</h2>${teamCards()}</div></div><div style="height:16px"></div>${taskTable()}`}
function teamPage(){return `<div class="card section"><h2>Đội ngũ & vai trò</h2><p style="color:var(--muted);margin-top:-6px">Nhấn vào từng người để xem dashboard theo đúng phạm vi vận hành.</p>${teamCards()}</div>`}
function placeholder(title,copy){return `<div class="card section"><h2>${title}</h2><div class="empty">${copy}<br><br><span class="badge">Backend Google đã kết nối · module này đang hoàn thiện</span></div></div>`}
function pageContent(d){if(state.page==='overview')return overview(d);if(state.page==='team')return teamPage();if(state.page==='tasks')return taskTable();if(state.page==='accounts')return placeholder('Trường & đơn vị','Dữ liệu sẽ lấy từ TRUONG + CO_HOI, gồm owner, pipeline, next action và hạn follow.');if(state.page==='finance')return placeholder('Công nợ','Dữ liệu sẽ lấy từ CONG_NO, gồm khoản phải thu, hạn thanh toán, hồ sơ thiếu và cash signal.');if(state.page==='reports')return placeholder('Báo cáo tuần','Dữ liệu sẽ lấy từ BAO_CAO_TUAN và draft tự động thứ Bảy.');return placeholder('AI Feed','Dữ liệu sẽ lấy từ AI_FEED để tổng hợp market changes, cash signals, execution risks và deadline.')}
function render(){const d=DATA[state.role]||DATA.ceo;if(!d){document.querySelector('#app').innerHTML='<div class="empty">Không tải được dữ liệu Google backend.</div>';return}document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="logo">S</div><div><b>SUNBOT OPS</b><small>Operations Intelligence</small></div></div><div class="nav">${nav()}</div><div class="sidebar-footer">V2 · GitHub Frontend<br>Google Sheets Backend</div></aside><main class="main"><header class="topbar"><div><span class="mobile-title">SUNBOT OPS</span><span class="badge">LIVE · GOOGLE BACKEND</span></div><div class="topbar-right"><select class="role-select" id="roleSelect"><option value="ceo">CEO · Vân</option><option value="dung">Dung · Bắc Miền Trung</option><option value="thu">Thu · Market/Trainer</option><option value="nhung">Nhung · Sales Ops</option></select><button class="logout" id="logout">Đăng xuất</button></div></header><div class="content"><section class="hero"><div><h1>Chào buổi chiều, ${d.shortName||d.name.split(' ').slice(-1)[0]}</h1><p>${d.role} · ${d.scope}</p><div class="status-line"><span class="pill">Dữ liệu trực tiếp từ SUNBOT_OPS_DATABASE</span><span class="pill">${META.updatedAt||''}</span></div></div></section>${pageContent(d)}</div></main></div>`;document.querySelector('#roleSelect').value=state.role;document.querySelector('#roleSelect').onchange=e=>{state.role=e.target.value;state.page='overview';render()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelectorAll('[data-role-card]').forEach(c=>c.onclick=()=>{state.role=c.dataset.roleCard;state.page='overview';render()});document.querySelector('#logout').onclick=()=>location.href=(META.logoutUrl||location.pathname);}
render();
