const DATA={
  ceo:{name:'Nguyễn Thị Tường Vân',role:'CEO · Kiro Việt Nam',scope:'Toàn hệ thống',kpis:[['Cần CEO','3','quyết định/điểm nghẽn'],['Đang thực hiện','5','ưu tiên điều hành'],['Đội ngũ chính','3','Dung · Thu · Nhung'],['Tín hiệu AI','3','thị trường · cash · execution']],attention:[
    ['red','Rà soát công nợ, hoa hồng và dòng tiền 1–7/2026','Chốt thứ tự ưu tiên thanh toán và thu hồi công nợ','12/08'],
    ['orange','Rà soát chính sách liên kết giáo dục/STEAM','Chốt địa bàn ưu tiên năm học 2026–2027','15/08'],
    ['orange','Phạm vi kế toán vận hành của Nhung','Xác nhận phần việc giữ nội bộ và phần giao kế toán thuế','11/08']
  ]},
  dung:{name:'Lê Thị Dung',role:'Trưởng nhóm Bắc Miền Trung · Market',scope:'Nghệ An · Bắc Miền Trung',kpis:[['Việc đang mở','2','1 đang làm · 1 mở'],['Ưu tiên thị trường','1','reconnect trường cũ'],['Cần CEO','0','không có điểm nghẽn'],['Địa bàn','BMT','Nghệ An trọng tâm']],attention:[['orange','Kết nối lại thị trường Nghệ An','Lập danh sách trường cũ, trường có khả năng tái triển khai và đầu mối cần gặp','15/08']]},
  thu:{name:'Minh Thu',role:'Market · Trainer',scope:'Đông Bắc · lân cận Hà Nội',kpis:[['Việc đang mở','2','1 pipeline · 1 đào tạo'],['Pipeline','1','khối tư thục'],['Cần CEO','0','không có điểm nghẽn'],['Vai trò','2','Market + Trainer']],attention:[['orange','Xây pipeline trường tư','Chốt khách hàng ưu tiên, trạng thái follow và bước tiếp theo','15/08']]},
  nhung:{name:'Hoàng Nhung',role:'Sales Operations · Ops Admin',scope:'Hà Nội',kpis:[['Việc đang mở','2','vận hành + tài chính'],['Cần CEO','1','phạm vi kế toán nội bộ'],['Địa bàn','HN','vận hành trường'],['Vai trò','2','Sales Ops + Ops Admin']],attention:[['red','Bàn giao kế toán vận hành','Chốt luồng hóa đơn, bảo hiểm, hồ sơ thanh toán và phối hợp kế toán thuế','15/08']]}
};
const TEAM=[
  {key:'dung',id:'TCH-LTD-012',name:'Lê Thị Dung',role:'Region Lead · Market',area:'Nghệ An · Bắc Miền Trung',open:2},
  {key:'thu',id:'TCH-NTA-014',name:'Minh Thu',role:'Market · Trainer',area:'Đông Bắc · lân cận Hà Nội',open:2},
  {key:'nhung',id:'UP-HOANG-NHUNG',name:'Hoàng Nhung',role:'Sales Ops · Ops Admin',area:'Hà Nội',open:2}
];
const TASKS=[
  ['1','Hoàn thiện SUNBOT OPS V2 và kiểm thử E2E','CEO','DOING','09/08','Có'],
  ['1','Hoàn thiện catalogue mô hình hợp tác và ma trận thương mại','CEO','OPEN','12/08','Không'],
  ['1','Rà soát chính sách liên kết giáo dục và cơ chế thu STEAM','CEO','DOING','15/08','Có'],
  ['2','Chốt vai trò, KPI và cơ chế phối hợp Nhung – Thu – Dung','CEO','OPEN','11/08','Không'],
  ['1','Rà soát công nợ, hoa hồng và dòng tiền 1–7/2026','CEO','OPEN','12/08','Có'],
  ['1','Kết nối lại thị trường Nghệ An và Bắc Miền Trung','Dung','DOING','15/08','Không'],
  ['2','Rà soát khả năng triển khai chương trình và sự kiện Nghệ An','Dung','OPEN','18/08','Không'],
  ['1','Xây pipeline trường tư tại Đông Bắc và lân cận Hà Nội','Thu','DOING','15/08','Không'],
  ['2','Chuẩn hóa quy trình đào tạo và chuyển giao','Thu','OPEN','20/08','Không'],
  ['1','Nhận lại vận hành trường Hà Nội sau thời gian nghỉ sinh','Nhung','DOING','12/08','Không'],
  ['1','Nhận bàn giao phần kế toán vận hành đơn giản','Nhung','OPEN','15/08','Có']
];
let state={role:'ceo',page:'overview'};
function visibleTasks(){if(state.role==='ceo')return TASKS;const owner={dung:'Dung',thu:'Thu',nhung:'Nhung'}[state.role];return TASKS.filter(t=>t[2]===owner)}
function nav(){return [['overview','⌂','Tổng quan'],['team','◎','Đội ngũ'],['tasks','✓','Công việc'],['accounts','▣','Trường & đơn vị'],['finance','₫','Công nợ'],['reports','▤','Báo cáo tuần'],['ai','✦','AI Feed']].map(x=>`<button data-page="${x[0]}" class="${state.page===x[0]?'active':''}">${x[1]} <span>${x[2]}</span></button>`).join('')}
function kpis(d){return `<div class="kpis">${d.kpis.map((k,i)=>`<div class="card kpi ${i===0?'accent':''}"><div class="label">${k[0]}</div><div class="value">${k[1]}</div><div class="hint">${k[2]}</div></div>`).join('')}</div>`}
function attention(d){return `<div class="card section"><h2>CEO Attention / Việc cần chú ý</h2><div class="attention">${d.attention.map(a=>`<div class="attention-item"><span class="dot ${a[0]}"></span><div><b>${a[1]}</b><small>${a[2]}</small></div><span class="deadline">${a[3]}</span></div>`).join('')}</div></div>`}
function teamCards(){return `<div class="team">${TEAM.map(p=>`<div class="person" data-role-card="${p.key}"><div class="avatar">${p.name.split(' ').slice(-1)[0].slice(0,1)}</div><h3>${p.name}</h3><p>${p.role}<br>${p.area}</p><div class="meta"><span class="mini">${p.id}</span><span class="mini">${p.open} việc mở</span></div></div>`).join('')}</div>`}
function taskTable(){const rows=visibleTasks();return `<div class="card section"><h2>Công việc ưu tiên</h2><div class="table-wrap"><table class="table"><thead><tr><th>Ưu tiên</th><th>Công việc</th><th>Owner</th><th>Trạng thái</th><th>Hạn</th><th>CEO</th></tr></thead><tbody>${rows.map(t=>`<tr><td class="priority">P${t[0]}</td><td>${t[1]}</td><td>${t[2]}</td><td><span class="tag ${t[3].toLowerCase()}">${t[3]}</span></td><td>${t[4]}</td><td>${t[5]==='Có'?'<span class="tag ceo">Cần CEO</span>':'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function overview(d){return `${kpis(d)}<div class="grid2">${attention(d)}<div class="card section"><h2>Đội ngũ vận hành</h2>${teamCards()}</div></div><div style="height:16px"></div>${taskTable()}`}
function teamPage(){return `<div class="card section"><h2>Đội ngũ & vai trò</h2><p style="color:var(--muted);margin-top:-6px">Nhấn vào từng người để xem dashboard theo đúng phạm vi vận hành.</p>${teamCards()}</div>`}
function placeholder(title,copy){return `<div class="card section"><h2>${title}</h2><div class="empty">${copy}<br><br><span class="badge">V2 · bước tiếp theo nối Google backend</span></div></div>`}
function pageContent(d){if(state.page==='overview')return overview(d);if(state.page==='team')return teamPage();if(state.page==='tasks')return taskTable();if(state.page==='accounts')return placeholder('Trường & đơn vị','Sẽ nối TRUONG + CO_HOI để quản lý trường, pipeline, next action và owner.');if(state.page==='finance')return placeholder('Công nợ','Sẽ nối CONG_NO để theo dõi khoản phải thu, hạn thanh toán, hồ sơ thiếu và tín hiệu dòng tiền.');if(state.page==='reports')return placeholder('Báo cáo tuần','Sẽ nối BAO_CAO_TUAN, tự tạo draft thứ Bảy và tổng hợp theo vai trò.');return placeholder('AI Feed','Sẽ nối AI_FEED để hiển thị market changes, cash signals, execution risks và deadline cho CEO.')}
function render(){const d=DATA[state.role];document.querySelector('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="logo">S</div><div><b>SUNBOT OPS</b><small>Operations Intelligence</small></div></div><div class="nav">${nav()}</div><div class="sidebar-footer">V2 Frontend · Mock data<br>Google backend sẽ nối ở Phase B</div></aside><main class="main"><header class="topbar"><div><span class="mobile-title">SUNBOT OPS</span><span class="badge">V2 · UI PREVIEW</span></div><div class="topbar-right"><select class="role-select" id="roleSelect"><option value="ceo">CEO · Vân</option><option value="dung">Dung · Bắc Miền Trung</option><option value="thu">Thu · Market/Trainer</option><option value="nhung">Nhung · Sales Ops</option></select><button class="logout" id="logout">Đăng xuất</button></div></header><div class="content"><section class="hero"><div><h1>Chào buổi chiều, ${d.name.split(' ').slice(-1)[0]}</h1><p>${d.role} · ${d.scope}</p><div class="status-line"><span class="pill">Dữ liệu mô phỏng từ vận hành Sunbot</span><span class="pill">08/08/2026</span></div></div></section>${pageContent(d)}</div></main></div>`;document.querySelector('#roleSelect').value=state.role;document.querySelector('#roleSelect').onchange=e=>{state.role=e.target.value;state.page='overview';render()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelectorAll('[data-role-card]').forEach(c=>c.onclick=()=>{state.role=c.dataset.roleCard;state.page='overview';render()});document.querySelector('#logout').onclick=()=>alert('Bản UI preview: đăng xuất thật sẽ hoạt động khi nối API authentication.');}
render();
