(function(){
  function currentRow(){const head=document.querySelector('#workspaceOverlay .workspace-head');if(!head)return null;const name=(head.querySelector('h2')?.textContent||'').trim();return(state.rows||[]).find(r=>String(r.ten_truong||'').trim()===name)||null;}
  function host(){return document.getElementById('wsSubpanel');}
  function canApprove(){const r=state.salesMeta&&state.salesMeta.role_class;return r==='ADMIN'||r==='LEADER';}
  function decorate(){const toolbar=document.querySelector('#workspaceOverlay.open .workspace-toolbar');if(!toolbar||document.getElementById('documentsBtn'))return;const row=currentRow();if(!row)return;const b=document.createElement('button');b.id='documentsBtn';b.className='btn secondary';b.textContent='Tài liệu';b.onclick=()=>openDocuments(row);toolbar.appendChild(b);}
  async function openDocuments(row){const h=host();h.innerHTML='<div class="subpanel open"><div class="subpanel-card"><div class="workspace-loading">Đang tải tài liệu…</div></div></div>';try{const docs=await call('documents','list',{outreach_id:row.outreach_id});render(row,docs||[]);}catch(e){h.innerHTML='';toast(e.message,true);}}
  function render(row,docs){const h=host();h.innerHTML=`<div class="subpanel open"><div class="subpanel-card"><div class="subpanel-head"><div><h3>Tài liệu gửi Nhà trường</h3><small class="muted">Phiếu sau meeting có thể gửi ngay. Proposal là bước riêng và phải được duyệt trước khi gửi.</small></div><button id="docClose">×</button></div><div class="document-actions"><button class="btn" id="makeThanks">Tạo phiếu sau meeting</button><button class="btn secondary" id="makeProposal">Tạo Proposal</button></div><div class="document-list">${docs.length?docs.map(d=>docRow(d,row)).join(''):'<div class="muted">Chưa có tài liệu được tạo.</div>'}</div></div></div>`;
    document.getElementById('docClose').onclick=()=>h.innerHTML='';document.getElementById('makeThanks').onclick=()=>makeThanks(row);document.getElementById('makeProposal').onclick=()=>proposalForm(row);
    document.querySelectorAll('[data-doc-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.docApprove));document.querySelectorAll('[data-doc-reject]').forEach(b=>b.onclick=()=>reject(b.dataset.docReject));
    document.querySelectorAll('[data-copy-pdf]').forEach(b=>b.onclick=()=>copyPdf(b.dataset.copyPdf));document.querySelectorAll('[data-thanks-email]').forEach(b=>b.onclick=()=>openThanksEmail(row,b.dataset.thanksEmail));
  }
  function docRow(d,row){const approved=String(d.status)==='APPROVED',pending=String(d.status)==='PENDING_APPROVAL',thanks=d.document_type==='MEETING_THANKS';return `<article class="document-row"><div><b>${d.document_type==='PROPOSAL'?'Proposal':'Phiếu ghi nhận sau meeting'}</b><span>${esc(d.reference||'')}</span><small>${esc(statusLabel(d.status))}</small></div><div class="document-links">${d.doc_url?`<a class="btn ghost" href="${esc(d.doc_url)}" target="_blank" rel="noopener">Google Doc</a>`:''}${d.pdf_url?`<a class="btn ghost" href="${esc(d.pdf_url)}" target="_blank" rel="noopener">Mở PDF</a>`:''}${thanks&&d.pdf_url?`<button class="btn ghost" data-copy-pdf="${esc(d.pdf_url)}">Copy link</button><button class="btn secondary" data-thanks-email="${esc(d.pdf_url)}">Email cảm ơn</button>`:''}${pending&&canApprove()?`<button class="btn secondary" data-doc-approve="${esc(d.document_id)}">Duyệt</button><button class="btn ghost" data-doc-reject="${esc(d.document_id)}">Trả lại</button>`:''}${approved?'<span class="doc-ok">Đã duyệt</span>':''}</div></article>`;}
  function statusLabel(s){return({READY_TO_SEND:'Sẵn sàng gửi',PENDING_APPROVAL:'Chờ duyệt',APPROVED:'Đã duyệt',NEEDS_REVISION:'Cần chỉnh sửa'})[String(s)]||String(s||'');}
  async function copyPdf(url){try{await navigator.clipboard.writeText(url);toast('Đã copy link PDF để gửi Zalo/tin nhắn.');}catch(e){prompt('Copy link PDF',url);}}
  function openThanksEmail(row,url){const to=String(row.email_truong||'').trim(),subject='Cảm ơn Nhà trường đã trao đổi cùng Sunbot – '+String(row.ten_truong||''),body=`Kính gửi Ban Giám hiệu ${row.ten_truong||'Nhà trường'},\n\nSunbot trân trọng cảm ơn Ban Giám hiệu đã dành thời gian trao đổi cùng bên em.\n\nEm xin gửi Phiếu ghi nhận nhu cầu sau buổi trao đổi để Nhà trường tiện xem lại và bổ sung/điều chỉnh nếu cần:\n${url}\n\nPhiếu này nhằm xác nhận những gì Sunbot đã hiểu; chưa phải đề xuất thương mại hay cam kết triển khai. Bên em sẽ tiếp tục thực hiện bước tiếp theo đã thống nhất với Nhà trường.\n\nTrân trọng,\nSunbot – Kiro Việt Nam`;
    window.open('https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(to)+'&su='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body),'_blank','noopener');
  }
  async function makeThanks(row){try{toast('Đang tạo phiếu chuyên nghiệp…');const r=await call('documents','createMeetingThanks',{outreach_id:row.outreach_id});toast('Đã tạo Phiếu ghi nhận sau meeting.');await openDocuments(row);if(r.pdf_url)window.open(r.pdf_url,'_blank','noopener');}catch(e){toast(e.message,true);}}
  function proposalForm(row){const h=host();h.innerHTML=`<div class="subpanel open"><div class="subpanel-card"><div class="subpanel-head"><div><h3>Tạo Proposal dự thảo</h3><small class="muted">Proposal lấy dữ liệu từ Discovery gần nhất và là hành động riêng sau Phiếu ghi nhận.</small></div><button id="propClose">×</button></div><label>Hướng triển khai khuyến nghị<textarea id="propModel" class="input textarea" placeholder="Ví dụ: Giáo viên nhà trường triển khai sau đào tạo + robot/học liệu cho khối 4–5 tuổi"></textarea></label><label>Cơ sở thương mại<textarea id="propCommercial" class="input textarea" placeholder="Ghi mã gói/báo giá hoặc phạm vi thương mại; chỉ dùng giá đã được phê duyệt"></textarea></label><label>Bước tiếp theo<textarea id="propNext" class="input textarea" placeholder="Ví dụ: gửi báo giá chính thức sau khi Nhà trường xác nhận quy mô 6 lớp"></textarea></label><div class="default-note">Proposal được tạo ở trạng thái <b>Chờ duyệt</b>. Admin có thể duyệt mọi proposal; Leader chỉ duyệt proposal do Staff thuộc nhóm mình tạo.</div><button class="btn full" id="propCreate">Tạo Proposal</button></div></div>`;document.getElementById('propClose').onclick=()=>openDocuments(row);document.getElementById('propCreate').onclick=async()=>{try{const r=await call('documents','createProposal',{outreach_id:row.outreach_id,recommended_model:document.getElementById('propModel').value,commercial_basis:document.getElementById('propCommercial').value,next_step:document.getElementById('propNext').value});toast('Proposal đã tạo và chuyển chờ duyệt.');await openDocuments(row);if(r.doc_url)window.open(r.doc_url,'_blank','noopener');}catch(e){toast(e.message,true);}};}
  async function approve(id){try{const r=await call('documents','approve',{document_id:id});toast(r.message||'Đã duyệt proposal.');const row=currentRow();if(row)openDocuments(row);}catch(e){toast(e.message,true);}}
  async function reject(id){const note=prompt('Ghi chú cần chỉnh sửa');if(note===null)return;try{await call('documents','reject',{document_id:id,note});toast('Đã trả lại proposal.');const row=currentRow();if(row)openDocuments(row);}catch(e){toast(e.message,true);}}
  const obs=new MutationObserver(()=>decorate());obs.observe(document.documentElement,{childList:true,subtree:true});
})();