(function(){
  let salesMeta=null;
  async function hydrateRole(){if(!state.token)return;try{salesMeta=await call('salesAdmin','bootstrap',{});state.salesMeta=salesMeta;if(salesMeta.role_class==='LEADER'){const d=await call('salesAdmin','accessRows',{});state.rows=d.rows||[];state.summary=d.summary||state.summary;state.generatedAt=d.generated_at||state.generatedAt;if(state.tab==='outreach'&&window.renderOutreach)window.renderOutreach();}decorateCards();}catch(e){console.warn('sales hierarchy',e);}}
  const baseLoad=window.loadApp;window.loadApp=async function(){await baseLoad();await hydrateRole();};
  const baseRefresh=window.refreshOutreach;window.refreshOutreach=async function(force){await baseRefresh(force);if(state.token&&state.salesMeta&&state.salesMeta.role_class==='LEADER'){try{const d=await call('salesAdmin','accessRows',{});state.rows=d.rows||[];state.summary=d.summary||state.summary;state.generatedAt=d.generated_at||state.generatedAt;if(state.tab==='outreach'&&window.renderOutreach)window.renderOutreach();}catch(e){toast(e.message,true);}}decorateCards();};
  const baseOpen=window.openAddSchool;window.openAddSchool=function(){baseOpen();setTimeout(enhanceAddSchool,40);};
  async function enhanceAddSchool(){const panel=document.querySelector('#workspaceOverlay.open .add-school-form');if(!panel||document.getElementById('newOwner'))return;try{const meta=state.salesMeta||await call('salesAdmin','bootstrap',{});state.salesMeta=meta;const users=meta.assignable||[];const details=panel.querySelector('.optional-details');const wrap=document.createElement('label');wrap.innerHTML=`Người phụ trách<select id="newOwner" class="input">${users.map(u=>`<option value="${esc(u.user_id)}" ${u.user_id===(state.boot?.user?.user_id)?'selected':''}>${esc(u.ho_ten)} · ${esc(u.role_class)}</option>`).join('')}</select>`;panel.insertBefore(wrap,details);const note=panel.querySelector('.default-note');if(note)note.innerHTML='<b>Phân công:</b><br>• Admin có thể gán cho Leader hoặc Staff<br>• Leader có thể giữ trường hoặc giao xuống Staff<br>• Staff chỉ tạo trường cho chính mình và không giao ngược lên Leader/Admin';const save=document.getElementById('saveNewSchool');if(save)save.onclick=saveWithOwner;}catch(e){toast('Chưa tải được danh sách người phụ trách: '+e.message,true);}}
  async function saveWithOwner(){const q=id=>document.getElementById(id),name=String(q('newSchoolName')?.value||'').trim(),province=String(q('newProvince')?.value||'').trim(),email=String(q('newSchoolEmail')?.value||'').trim(),phone=String(q('newSchoolPhone')?.value||'').trim(),owner=String(q('newOwner')?.value||'');if(name.length<3)return toast('Hãy nhập tên trường.',true);if(province.length<2)return toast('Hãy nhập tỉnh/thành.',true);try{const r=await call('outreachCreate','',{ten_truong:name,tinh_thanh:province,email_truong:email,dien_thoai_dau_moi:phone,owner_user_id:owner});document.getElementById('workspaceOverlay')?.classList.remove('open');document.body.classList.remove('workspace-open');await window.refreshOutreach(true);toast(r.message||'Đã thêm trường.');}catch(e){toast(e.message,true);}}
  function decorateCards(){if(!state.salesMeta||state.salesMeta.role_class!=='LEADER')return;document.querySelectorAll('.school-card').forEach(card=>{if(card.querySelector('.leader-owner'))return;const row=(state.rows||[]).find(r=>String(r.outreach_id)===String(card.dataset.id));if(!row||!row.owner_name)return;const badges=card.querySelector('.badges');if(badges){const s=document.createElement('span');s.className='badge owner-badge leader-owner';s.textContent=row.owner_name;badges.appendChild(s);}});}
  const obs=new MutationObserver(()=>{decorateCards();if(document.querySelector('#workspaceOverlay.open .add-school-form'))enhanceAddSchool();});obs.observe(document.documentElement,{childList:true,subtree:true});
})();