(function(){
  function rowFromWorkspace(){const head=document.querySelector('#workspaceOverlay .workspace-head');if(!head)return null;const name=(head.querySelector('h2')?.textContent||'').trim();const badges=[...head.querySelectorAll('.badge')].map(x=>(x.textContent||'').trim());const province=badges.length>1?badges[1]:'';return(state.rows||[]).find(r=>String(r.ten_truong||'').trim()===name&&(!province||String(r.tinh_thanh||'').trim()===province))||(state.rows||[]).find(r=>String(r.ten_truong||'').trim()===name)||null;}
  function decorate(){const toolbar=document.querySelector('#workspaceOverlay.open .workspace-toolbar');if(!toolbar||document.getElementById('timelineBtn'))return;const row=rowFromWorkspace();if(!row)return;const b=document.createElement('button');b.id='timelineBtn';b.className='btn ghost';b.textContent='🕘 Lịch sử';b.onclick=()=>openTimeline(row);toolbar.appendChild(b);}
  async function openTimeline(row){const host=document.getElementById('wsSubpanel');host.innerHTML='<div class="subpanel open"><div class="subpanel-card compact"><div class="workspace-loading">Đang tải lịch sử trường…</div></div></div>';try{const d=await call('timeline','get',{outreach_id:row.outreach_id});render(d)}catch(e){host.innerHTML='';toast(e.message,true)}}
  function render(d){const host=document.getElementById('wsSubpanel'),stage=d.funnel_stage||{};host.innerHTML=`<div class="subpanel open"><div class="subpanel-card"><div class="subpanel-head"><div><h3>Lịch sử & bước tiếp theo</h3><small class="muted">Trạng thái hành trình: <b>${esc(stage.label||'')}</b></small></div><button id="tlClose">×</button></div>
    ${d.latest_discovery&&!d.opportunities.length?`<div class="default-note"><b>Discovery đã hoàn thành.</b><br>Có thể chuyển thẳng thành cơ hội mà không nhập lại cấu hình và bước tiếp theo.<br><button class="btn" id="tlCreateOpp" style="margin-top:10px">Tạo cơ hội từ Discovery</button></div>`:''}
    <h4>Việc sắp tới</h4><div class="timeline-upcoming">${d.upcoming.length?d.upcoming.map(x=>`<div class="tl-item future"><div class="tl-dot"></div><div><b>${esc(x.title)}</b><small>Hạn ${esc(x.due||'—')}</small>${x.next?`<p>${esc(x.next)}</p>`:''}</div></div>`).join(''):'<div class="muted">Không có việc đang mở.</div>'}</div>
    <h4>Lịch sử tương tác</h4><div class="timeline-list">${d.history.length?d.history.map(x=>`<div class="tl-item"><div class="tl-dot"></div><div><small>${esc(formatTime(x.time))}</small><b>${esc(x.title)}</b><p>${esc(x.detail)}</p>${x.next?`<em>Bước tiếp: ${esc(x.next)}${x.due?' · '+esc(x.due):''}</em>`:''}${x.evidence?`<a href="${esc(x.evidence)}" target="_blank" rel="noopener">Mở tài liệu đã gửi</a>`:''}</div></div>`).join(''):'<div class="muted">Chưa có lịch sử được ghi nhận.</div>'}</div></div></div>`;
    document.getElementById('tlClose').onclick=()=>host.innerHTML='';document.getElementById('tlCreateOpp')?.addEventListener('click',()=>createOpp(d.outreach.outreach_id));}
  async function createOpp(id){if(!confirm('Tạo cơ hội từ kết quả Discovery gần nhất?'))return;try{const r=await call('timeline','opportunityFromDiscovery',{outreach_id:id});toast(r.message);const d=await call('timeline','get',{outreach_id:id});render(d);if(window.refreshOutreach)await window.refreshOutreach(true)}catch(e){toast(e.message,true)}}
  function formatTime(v){if(!v)return'';try{const d=new Date(v);if(isNaN(d))return v;return d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return v}}
  const obs=new MutationObserver(()=>decorate());obs.observe(document.documentElement,{subtree:true,childList:true});
})();
