export const API={
  url:'https://script.google.com/macros/s/AKfycbw32BGSXwFVOpRCknx5hn8-k2m5ZXox26_y2mnZKVWL0JKHCv_Qtly5JiY0FS9e87kU/exec',
  token:sessionStorage.getItem('sunbot_school_v2_token')||'',pending:new Map(),ready:false,
  init(){if(this.ready)return;this.ready=true;window.addEventListener('message',e=>{const m=e.data||{};if(m.type!=='sunbot-pages-response'||!m.requestId)return;const p=this.pending.get(m.requestId);if(!p)return;clearTimeout(p.timer);p.frame.remove();this.pending.delete(m.requestId);m.ok?p.resolve(m.result):p.reject(new Error(m.error||'Không thể xử lý yêu cầu.'));});},
  setToken(t){this.token=t||'';if(t)sessionStorage.setItem('sunbot_school_v2_token',t);else sessionStorage.removeItem('sunbot_school_v2_token');},
  call(subaction,payload={},timeout=15000){this.init();return new Promise((resolve,reject)=>{const id='v2_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8),frame=document.createElement('iframe');frame.name=id;frame.style.display='none';document.body.appendChild(frame);const form=document.createElement('form');form.method='POST';form.action=this.url;form.target=id;form.style.display='none';const fields={action:'pagesBridge',request_id:id,mode:'v2',subaction,token:this.token,payload:JSON.stringify(payload||{})};Object.entries(fields).forEach(([k,v])=>{const input=document.createElement('input');input.type='hidden';input.name=k;input.value=v;form.appendChild(input)});document.body.appendChild(form);const timer=setTimeout(()=>{this.pending.delete(id);frame.remove();reject(new Error('Máy chủ phản hồi quá chậm.'))},timeout);this.pending.set(id,{resolve,reject,frame,timer});form.submit();form.remove();});},
  async login(loginId,password){const r=await this.call('auth.login',{login_id:loginId,password});this.setToken(r.token);return r;},
  bootstrap(){return this.call('app.bootstrap')},today(){return this.call('today.list')},schools(){return this.call('schools.list')},schoolDetail(id){return this.call('schools.detail',{school_id:id})},createSchool(p){return this.call('schools.create',p)},createInteraction(p){return this.call('interactions.create',p)},createAction(p){return this.call('next_actions.create',p)},completeAction(id){return this.call('next_actions.complete',{action_id:id})},adminUsers(){return this.call('admin.users')}
};
