import {API} from './api.js';

const state={boot:null,user:null,tab:'today',schools:[],today:[],selected:null,loading:false};
const app=document.getElementById('app');
const statusMap={TARGET:'Mục tiêu',CONTACTED:'Đã tiếp cận',ENGAGED:'Đang quan tâm',DISCOVERY:'Khám phá nhu cầu',OPPORTUNITY:'Cơ hội',CUSTOMER:'Khách hàng',NURTURE:'Nuôi dưỡng',CLOSED:'Đã đóng'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=v=>{if(!v)return'Chưa có hạn';const d=new Date(String(v).slice(0,10)+'T00:00:00');return isNaN(d)?String(v):d.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'})};
const initials=n=>String(n||'SV').trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();
function toast(msg,error=false){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast'+(error?' error':'');t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3200)}
function loading(on=true){document.querySelector('.loading-line')?.remove();if(!on)return;const x=document.createElement('div');x.className='loading-line';document.body.prepend(x)}

async function start(){if(!API.token)return renderLogin();try{loading();state.boot=await API.bootstrap();state.user=state.boot.user;await loadCore();renderShell();}catch(e){API.setToken('');renderLogin(e.message)}finally{loading(false)}}
function renderLogin(error=''){
  app.innerHTML=`<main class="login-shell"><section class="login-visual"><div><div class="eyebrow" style="color:#9ED7FF">SUNBOT SCHOOL DEVELOPMENT OS</div><h1>Quản lý trường theo một luồng duy nhất.</h1><p>School → Interaction → Next Action → Discovery → Opportunity → Proposal → Decision.</p></div><div class="login-principles"><div><strong>Rõ người</strong><br>Mỗi trường luôn có người phụ trách.</div><div><strong>Rõ việc</strong><br>Mỗi trường active luôn có việc tiếp theo và hạn.</div><div><strong>Rõ cơ hội</strong><br>Chỉ tạo cơ hội khi nhu cầu đã đủ rõ.</div></div></section><section class="login-panel"><form class="login-card" id="loginForm"><div class="login-brand"><div class="brand-mark"><span style="font-weight:900;color:#1D6FE8">SUNBOT</span></div><strong>SUNBOT SCHOOL OS</strong></div><h2>Đăng nhập</h2><p>Dùng ID email và mật khẩu do Admin cấp. Hệ thống không gửi mã qua email.</p><div class="field"><label>ID đăng nhập</label><input id="loginId" autocomplete="username" placeholder="tuongvan1906@gmail.com"></div><div class="field"><label>Mật khẩu</label><input id="password" type="password" inputmode="numeric" autocomplete="current-password" placeholder="••••••"></div>${error?`<p style="color:#C43D3D">${esc(error)}</p>`:''}<button class="btn btn-primary" type="submit">Đăng nhập</button></form></section></main>`;
  document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const id=document.getElementById('loginId').value.trim(),pw=document.getElementById('password').value.trim();if(!id||!pw)return toast('Cần nhập ID và mật khẩu.',true);try{loading();const r=await API.login(id,pw);state.user=r.user;state.boot=await API.bootstrap();await loadCore();renderShell();toast('Đăng nhập thành công.');}catch(err){toast(err.message,true)}finally{loading(false)}};
}
async function loadCore(){const [schools,today]=await Promise.all([API.schools(),API.today()]);state.schools=schools||[];state.today=today||[];}
function renderShell(){
  const u=state.user||{};app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark"><span style="font-size:10px;font-weight:900;color:#1D6FE8">SUNBOT</span></div><div class="brand-copy"><strong>SUNBOT SCHOOL OS</strong><span>Phát triển trường & cơ hội</span></div></div><div class="top-actions"><button class="icon-btn" id="refresh" title="Làm mới">↻</button><div class="avatar">${initials(u.display_name)}</div></div></header><div class="layout"><aside class="sidebar"><nav class="nav-group">${nav('today','⌁','Hôm nay')}${nav('schools','⌂','Trường')}${nav('opportunities','◇','Cơ hội')}${u.role_code==='ADMIN'?nav('admin','⚙','Quản trị'):''}</nav><div class="sidebar-foot"><strong>Nguyên tắc vận hành</strong><br>Mỗi trường active phải có người phụ trách và một việc tiếp theo có hạn.</div></aside><main class="main" id="main"></main></div></div>`;
  document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderShell()});document.getElementById('refresh').onclick=refresh;renderPage();
}
function nav(tab,icon,label){return `<button class="nav-btn ${state.tab===tab?'active':''}" data-tab="${tab}"><span>${icon}</span><span>${label}</span></button>`}
function renderPage(){if(state.tab==='today')renderToday();else if(state.tab==='schools')renderSchools();else if(state.tab==='opportunities')renderOpps();else renderAdmin()}
async function refresh(){try{loading();await loadCore();renderShell();toast('Đã làm mới.');}catch(e){toast(e.message,true)}finally{loading(false)}}

function renderToday(){const overdue=state.schools.filter(x=>x.overdue).length,dueToday=state.today.filter(x=>!x.overdue).length,waiting=state.schools.filter(x=>['CONTACTED','ENGAGED'].includes(x.relationship_state)).length,discovering=state.schools.filter(x=>x.relationship_state==='DISCOVERY').length;document.getElementById('main').innerHTML=`<section class="page-head"><div><div class="eyebrow">HÔM NAY</div><h1>Chào ${esc(shortName(state.user.display_name))}, đây là việc cần ưu tiên.</h1><p>Chỉ đưa lên những trường đang cần hành động. Không biến dashboard thành báo cáo để đọc.</p></div><button class="btn btn-primary" id="addSchool">+ Thêm trường</button></section><section class="kpi-grid"><div class="kpi danger"><strong>${overdue}</strong><span>Việc quá hạn</span></div><div class="kpi warning"><strong>${dueToday}</strong><span>Đến hạn hôm nay</span></div><div class="kpi"><strong>${waiting}</strong><span>Chờ phản hồi</span></div><div class="kpi"><strong>${discovering}</strong><span>Khám phá nhu cầu</span></div></section><section class="panel"><div class="panel-head"><div><h2>Việc cần xử lý</h2><p>Sắp theo hạn; mở trường để ghi nhận tương tác hoặc đặt việc tiếp theo.</p></div></div><div class="panel-body">${state.today.length?table(state.today):'<div class="empty">Không có việc đến hạn hôm nay.</div>'}</div></section>`;bindOpen();document.getElementById('addSchool').onclick=openAddSchool}
function shortName(v){const a=String(v||'').trim().split(/\s+/);return a[a.length-1]||''}
function renderSchools(){document.getElementById('main').innerHTML=`<section class="page-head"><div><div class="eyebrow">SCHOOL DEVELOPMENT</div><h1>Trường</h1><p>School + Owner + trạng thái quan hệ + Next Action là lõi vận hành.</p></div><button class="btn btn-primary" id="addSchool">+ Thêm trường</button></section><section class="panel"><div class="panel-head"><div><h2>Danh sách trường</h2><p>${state.schools.length} trường trong phạm vi quyền hiện tại.</p></div></div><div class="panel-body"><div class="toolbar"><div class="search"><input id="q" placeholder="Tìm trường, địa bàn, người phụ trách, việc tiếp theo…"></div><select id="status"><option value="">Tất cả trạng thái</option>${Object.entries(statusMap).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div id="results">${table(state.schools)}</div></div></section>`;document.getElementById('addSchool').onclick=openAddSchool;const f=()=>{const q=document.getElementById('q').value.toLowerCase().trim(),s=document.getElementById('status').value;const rows=state.schools.filter(r=>(!q||[r.school_name,r.province,r.current_owner_name,r.next_action].join(' ').toLowerCase().includes(q))&&(!s||r.relationship_state===s));document.getElementById('results').innerHTML=rows.length?table(rows):'<div class="empty">Không có trường phù hợp.</div>';bindOpen()};document.getElementById('q').oninput=f;document.getElementById('status').onchange=f;bindOpen()}
function table(rows){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Trường</th><th>Phụ trách</th><th>Trạng thái</th><th>Việc tiếp theo</th><th>Hạn</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="school-name">${esc(r.school_name)}</div><div class="subtle">${esc(r.province||'')}</div></td><td>${esc(r.current_owner_name||'Chưa giao')}</td><td><span class="status ${String(r.relationship_state||'target').toLowerCase()}">${esc(statusMap[r.relationship_state]||r.relationship_state)}</span></td><td class="next-action">${esc(r.next_action||'Chưa có việc tiếp theo')}</td><td class="due ${r.overdue?'overdue':''}">${r.overdue?'Quá hạn · ':''}${esc(fmt(r.next_action_date))}</td><td><button class="btn btn-ghost open-school" data-id="${esc(r.school_id)}">Mở</button></td></tr>`).join('')}</tbody></table></div>`}
function bindOpen(){document.querySelectorAll('.open-school').forEach(b=>b.onclick=()=>openSchool(b.dataset.id))}

async function openSchool(id){try{loading();const data=await API.schoolDetail(id),r=data.school;state.selected=r;const o=document.createElement('div');o.className='drawer-backdrop';o.innerHTML=`<aside class="drawer"><header class="drawer-head"><div><div class="eyebrow">HỒ SƠ TRƯỜNG</div><h2>${esc(r.school_name)}</h2><div class="school-meta"><span class="meta-pill">${esc(r.province||'')}</span><span class="meta-pill">Phụ trách: ${esc(r.current_owner_name||'Chưa giao')}</span><span class="status ${String(r.relationship_state).toLowerCase()}">${esc(statusMap[r.relationship_state]||r.relationship_state)}</span></div></div><button class="icon-btn close">×</button></header><div class="drawer-body"><section class="next-box"><div class="label">Việc tiếp theo</div><strong>${esc(r.next_action||'Chưa có việc tiếp theo')}</strong><div class="due ${r.overdue?'overdue':''}">${r.overdue?'Quá hạn · ':''}${esc(fmt(r.next_action_date))}</div></section><div class="action-row"><button class="btn btn-primary" id="interaction">Ghi nhận tương tác</button><button class="btn btn-secondary" id="next">Đặt việc tiếp theo</button><button class="btn btn-secondary" id="discovery">Khám phá nhu cầu</button>${r.relationship_state==='DISCOVERY'?'<button class="btn btn-secondary" id="opp">Tạo cơ hội</button>':''}</div><section class="section"><h3>Lịch sử tương tác</h3><div class="timeline">${(data.interactions||[]).length?(data.interactions||[]).map(i=>`<div class="timeline-item"><div class="timeline-time">${esc(formatTime(i.interaction_at))}</div><div class="timeline-content"><strong>${esc(i.interaction_type||'Tương tác')} · ${esc(i.summary||'')}</strong>${i.result?`<p>${esc(i.result)}</p>`:''}</div></div>`).join(''):'<div class="empty">Chưa có tương tác nào được ghi nhận.</div>'}</div></section></div></aside>`;document.body.appendChild(o);o.querySelector('.close').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};o.querySelector('#interaction').onclick=()=>interactionForm(r,o);o.querySelector('#next').onclick=()=>nextForm(r,o);o.querySelector('#discovery').onclick=()=>toast('Discovery Wizard sẽ được bật ở Phase 2 sau khi Phase 1 E2E pass.');o.querySelector('#opp')?.addEventListener('click',()=>toast('Cơ hội chỉ được tạo từ Discovery đã xác nhận.'));}catch(e){toast(e.message,true)}finally{loading(false)}}
function formatTime(v){if(!v)return'';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function modal(title,body,onSave){const o=document.createElement('div');o.className='drawer-backdrop';o.innerHTML=`<aside class="drawer" style="width:min(560px,100%)"><header class="drawer-head"><div><div class="eyebrow">SUNBOT SCHOOL OS</div><h2>${esc(title)}</h2></div><button class="icon-btn close">×</button></header><div class="drawer-body">${body}</div></aside>`;document.body.appendChild(o);o.querySelector('.close').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};o.querySelector('[data-save]')?.addEventListener('click',()=>onSave(o));return o}
function interactionForm(r,parent){modal('Ghi nhận tương tác',`<div class="form-grid"><div class="field"><label>Loại tương tác</label><select id="type"><option>Gọi điện</option><option>Email</option><option>Zalo</option><option>Meeting</option><option>Demo</option><option>Gặp trực tiếp</option></select></div><div class="field"><label>Thời điểm</label><input id="at" type="datetime-local"></div><div class="field full"><label>Điều đã xảy ra</label><textarea id="summary" placeholder="Ghi sự thật, ngắn và cụ thể…"></textarea></div><div class="field full"><label>Kết quả / điều học được</label><textarea id="result" placeholder="Nhà trường phản hồi gì? Có thông tin nào giá trị cho lần tiếp cận sau?"></textarea></div></div><div class="form-actions"><button class="btn btn-primary" data-save>Lưu tương tác</button></div>`,async m=>{const summary=m.querySelector('#summary').value.trim();if(!summary)return toast('Cần ghi điều đã xảy ra.',true);try{loading();await API.createInteraction({school_id:r.school_id,interaction_type:m.querySelector('#type').value,interaction_at:m.querySelector('#at').value||new Date().toISOString(),summary,result:m.querySelector('#result').value.trim()});m.remove();parent.remove();await loadCore();renderShell();toast('Đã ghi nhận tương tác.');}catch(e){toast(e.message,true)}finally{loading(false)}})}
function nextForm(r,parent){modal('Đặt việc tiếp theo',`<div class="form-grid"><div class="field full"><label>Việc cần làm</label><input id="action" value="${esc(r.next_action||'')}"></div><div class="field"><label>Hạn</label><input id="due" type="date" value="${esc(r.next_action_date||'')}"></div><div class="field"><label>Ưu tiên</label><select id="priority"><option>P1</option><option selected>P2</option><option>P3</option></select></div></div><div class="form-actions"><button class="btn btn-primary" data-save>Lưu việc tiếp theo</button></div>`,async m=>{const a=m.querySelector('#action').value.trim(),d=m.querySelector('#due').value;if(!a||!d)return toast('Việc tiếp theo cần có nội dung và ngày.',true);try{loading();await API.createAction({school_id:r.school_id,action_text:a,due_date:d,priority:m.querySelector('#priority').value});m.remove();parent.remove();await loadCore();renderShell();toast('Đã cập nhật việc tiếp theo.');}catch(e){toast(e.message,true)}finally{loading(false)}})}
function openAddSchool(){modal('Thêm trường',`<div class="form-grid"><div class="field full"><label>Tên trường *</label><input id="name" placeholder="Ví dụ: Mầm non Hoa Sen"></div><div class="field"><label>Tỉnh/thành *</label><input id="province" placeholder="Hà Nội"></div><div class="field"><label>Loại hình</label><select id="type"><option>Công lập</option><option>Tư thục</option><option>Quốc tế</option></select></div></div><div class="form-actions"><button class="btn btn-primary" data-save>Thêm trường</button></div>`,async m=>{const name=m.querySelector('#name').value.trim(),province=m.querySelector('#province').value.trim();if(!name||!province)return toast('Tên trường và tỉnh/thành là bắt buộc.',true);try{loading();await API.createSchool({school_name:name,province,school_type:m.querySelector('#type').value});m.remove();await loadCore();renderShell();toast('Đã thêm trường. Hãy đặt việc tiếp theo.');}catch(e){toast(e.message,true)}finally{loading(false)}})}
function renderOpps(){document.getElementById('main').innerHTML=`<section class="page-head"><div><div class="eyebrow">CƠ HỘI</div><h1>Cơ hội đủ điều kiện</h1><p>Chỉ xuất hiện sau Khám phá nhu cầu có Need Statement rõ. Phase 3 sẽ nối Opportunity lifecycle.</p></div></section><section class="panel"><div class="empty">Phase 1 chưa bật tạo cơ hội.</div></section>`}
async function renderAdmin(){const host=document.getElementById('main');host.innerHTML=`<section class="page-head"><div><div class="eyebrow">QUẢN TRỊ</div><h1>Người dùng & phân quyền</h1><p>ID đăng nhập là email. Admin quản lý Leader/Staff và quyền giao trường.</p></div></section><section class="panel"><div class="panel-body"><div class="empty">Đang tải người dùng…</div></div></section>`;try{const users=await API.adminUsers();host.querySelector('.panel-body').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Người dùng</th><th>ID đăng nhập</th><th>Vai trò</th><th>Quản lý bởi</th><th>Trạng thái</th></tr></thead><tbody>${users.map(u=>`<tr><td class="school-name">${esc(u.display_name)}</td><td>${esc(u.login_id)}</td><td>${esc(u.role_code)}</td><td>${esc(u.manager_user_id||'—')}</td><td>${u.active?'Đang hoạt động':'Đã khóa'}</td></tr>`).join('')}</tbody></table></div>`}catch(e){toast(e.message,true)}}

start();
