const DOC_ENGINE=Object.freeze({
  SHEET:'DOCUMENT_OUTPUT',
  HEADERS:['document_id','document_type','reference','version','account_id','outreach_id','discovery_id','owner_user_id','created_by_user_id','status','approval_note','approved_by_user_id','approved_at','doc_url','pdf_url','created_at','updated_at'],
  LOGO:'https://sunbotvietnam.github.io/portal/profile/assets/images/logo-sunbot.png'
});
function apiSessionDocuments(sessionToken,action,payload){const user=authenticateSession_(sessionToken);payload=payload||{};ensureDocumentSheet_();switch(String(action||'')){case'list':return documentList_(user,payload);case'createMeetingThanks':return documentCreateMeetingThanks_(user,payload);case'createProposal':return documentCreateProposal_(user,payload);case'approve':return documentApprove_(user,payload);case'reject':return documentReject_(user,payload);default:throw new Error('Tác vụ tài liệu không hợp lệ.');}}
function ensureDocumentSheet_(){const ss=getDb_();let sh=ss.getSheetByName(DOC_ENGINE.SHEET);if(!sh){sh=ss.insertSheet(DOC_ENGINE.SHEET);sh.appendRow(DOC_ENGINE.HEADERS);sh.setFrozenRows(1);}const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);DOC_ENGINE.HEADERS.forEach(function(x){if(!h.includes(x))sh.getRange(1,sh.getLastColumn()+1).setValue(x);});return sh;}
function docCanSee_(user,r){if(roleClass_(user)==='ADMIN')return true;if(String(r.owner_user_id)===String(user.user_id)||String(r.created_by_user_id)===String(user.user_id))return true;return false;}
function documentList_(user,p){let rows=getAll_(DOC_ENGINE.SHEET).filter(function(r){return r.document_id&&docCanSee_(user,r);});if(p.outreach_id)rows=rows.filter(function(r){return String(r.outreach_id)===String(p.outreach_id);});if(p.status)rows=rows.filter(function(r){return String(r.status)===String(p.status);});return rows.sort(function(a,b){return String(b.created_at).localeCompare(String(a.created_at));}).slice(0,200);}
function documentContext_(user,p){required_(p,['outreach_id']);const row=findOne_(OUTREACH.SHEET,'outreach_id',p.outreach_id);assertOutreachOwner_(user,row);const account=row.account_id?findOne_('TRUONG','account_id',row.account_id):{};const discoveries=getAll_(ENGAGEMENT.DISCOVERY_SHEET).filter(function(d){return String(d.outreach_id)===String(row.outreach_id);}).sort(function(a,b){return String(b.completed_at).localeCompare(String(a.completed_at));});const d=discoveries[0]||{};let answers={};try{answers=JSON.parse(String(d.answers_json||'{}'));}catch(e){}return{row:row,account:account||{},discovery:d,answers:answers};}
function documentFolder_(){const root=DriveApp.getFolderById(PRODUCTION.ROOT_FOLDER_ID);const it=root.getFoldersByName('06_SCHOOL_OUTPUTS');return it.hasNext()?it.next():root.createFolder('06_SCHOOL_OUTPUTS');}
function documentRef_(type){const code=type==='PROPOSAL'?'PROP':'MEET';return'SB-'+code+'-'+Utilities.formatDate(new Date(),APP.TZ,'yyyyMMdd')+'-'+Utilities.getUuid().slice(0,5).toUpperCase();}
function docBase_(ctx,title,reference){const doc=DocumentApp.create(title+' – '+ctx.row.ten_truong);const body=doc.getBody();try{const blob=UrlFetchApp.fetch(DOC_ENGINE.LOGO,{muteHttpExceptions:true}).getBlob();body.appendImage(blob).setWidth(120);}catch(e){}body.appendParagraph('SUNBOT · KIRO VIỆT NAM').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph(title).setHeading(DocumentApp.ParagraphHeading.TITLE);const meta=body.appendTable([['Mã tài liệu',reference],['Nhà trường',String(ctx.row.ten_truong||'')],['Ngày',Utilities.formatDate(new Date(),APP.TZ,'dd/MM/yyyy')],['Phiên bản','1.0']]);meta.setBorderWidth(0.5);body.appendHorizontalRule();return{doc:doc,body:body};}
function addSection_(body,title,text){body.appendParagraph(title).setHeading(DocumentApp.ParagraphHeading.HEADING2);String(text||'Chưa ghi nhận').split('\n').filter(Boolean).forEach(function(x){body.appendParagraph(x);});}
function saveDocPdf_(doc,reference){doc.saveAndClose();const folder=documentFolder_();const file=DriveApp.getFileById(doc.getId());file.moveTo(folder);const pdf=folder.createFile(file.getAs(MimeType.PDF).setName(reference+'.pdf'));return{doc_url:file.getUrl(),pdf_url:pdf.getUrl()};}
function appendDocRecord_(user,ctx,type,reference,status,urls){const id=id_('DOC');append_(DOC_ENGINE.SHEET,{document_id:id,document_type:type,reference:reference,version:'1.0',account_id:ctx.row.account_id||'',outreach_id:ctx.row.outreach_id,discovery_id:ctx.discovery.discovery_id||'',owner_user_id:ctx.row.owner_user_id||user.user_id,created_by_user_id:user.user_id,status:status,approval_note:'',approved_by_user_id:'',approved_at:'',doc_url:urls.doc_url,pdf_url:urls.pdf_url,created_at:now_(),updated_at:now_()});audit_(user,'CREATE_DOCUMENT',DOC_ENGINE.SHEET,id,{type:type,reference:reference,status:status});return id;}
function documentCreateMeetingThanks_(user,p){const c=documentContext_(user,p),ref=documentRef_('MEETING'),x=docBase_(c,'PHIẾU GHI NHẬN SAU BUỔI TRAO ĐỔI',ref),a=c.answers,d=c.discovery;addSection_(x.body,'Lời cảm ơn','Sunbot trân trọng cảm ơn Ban Giám hiệu Nhà trường đã dành thời gian trao đổi. Phiếu này ghi lại những nội dung Sunbot đã hiểu để Nhà trường có thể kiểm tra, bổ sung hoặc điều chỉnh khi cần.');addSection_(x.body,'1. Nhu cầu Sunbot đã ghi nhận',a.need_statement||d.need_statement||'Chưa có bản tóm tắt nhu cầu.');addSection_(x.body,'2. Các ưu tiên đã trao đổi','Mục tiêu: '+String(d.muc_tieu||'')+'\nMô hình giáo viên: '+String(d.mo_hinh_giao_vien||'')+'\nQuy mô dự kiến: '+String(d.quy_mo_bat_dau||'')+'\nThời điểm: '+String(d.thoi_diem||''));addSection_(x.body,'3. Điều Nhà trường có thể bổ sung','Nếu có nội dung cần điều chỉnh, Nhà trường vui lòng phản hồi lại người phụ trách Sunbot. Việc ghi nhận này chưa phải đề xuất thương mại và không tạo nghĩa vụ triển khai.');addSection_(x.body,'4. Bước tiếp theo đã thống nhất',String(d.buoc_tiep_theo||a.buoc_tiep_theo||'Chưa xác định')+(a.han_buoc_tiep_theo?' – dự kiến '+a.han_buoc_tiep_theo:''));x.body.appendParagraph('Trân trọng,\nSunbot – Công ty Cổ phần Công nghệ Giáo dục Kiro Việt Nam');const urls=saveDocPdf_(x.doc,ref),id=appendDocRecord_(user,c,'MEETING_THANKS',ref,'READY_TO_SEND',urls);return{ok:true,document_id:id,reference:ref,doc_url:urls.doc_url,pdf_url:urls.pdf_url,message:'Đã tạo Phiếu ghi nhận sau meeting.'};}
function documentCreateProposal_(user,p){const c=documentContext_(user,p),ref=documentRef_('PROPOSAL'),x=docBase_(c,'ĐỀ XUẤT HỢP TÁC SUNBOT',ref),a=c.answers,d=c.discovery;addSection_(x.body,'1. Bối cảnh và nhu cầu Nhà trường',a.need_statement||d.need_statement||'Nhu cầu sẽ được hoàn thiện theo kết quả trao đổi với Nhà trường.');addSection_(x.body,'2. Hướng triển khai được khuyến nghị',String(p.recommended_model||a.cau_hinh_quan_tam||d.cau_hinh_quan_tam||'Sunbot sẽ cấu hình theo nhu cầu đã xác nhận.'));addSection_(x.body,'3. Cấu phần đề xuất','Chương trình: Lập trình tư duy cùng Sunbot và/hoặc STEAM Sáng tạo cùng Sunbot theo phạm vi phù hợp.\nMô hình giáo viên: '+String(d.mo_hinh_giao_vien||'Sẽ thống nhất')+'\nQuy mô khởi đầu: '+String(d.quy_mo_bat_dau||'Sẽ thống nhất')+'\nThời điểm: '+String(d.thoi_diem||'Sẽ thống nhất'));addSection_(x.body,'4. Phân định trách nhiệm','Sunbot chịu trách nhiệm về chương trình, học liệu, đào tạo/hỗ trợ và các cấu phần đã được nêu trong phương án. Nhà trường bố trí đầu mối, lịch, không gian, giáo viên/trẻ và các thủ tục nội bộ theo mô hình lựa chọn. Các nội dung ngoài phạm vi phải được hai bên xác nhận trước khi thực hiện.');addSection_(x.body,'5. Cơ sở thương mại',String(p.commercial_basis||'Báo giá chính thức sẽ được lập theo cấu hình được duyệt và bảng giá Sunbot hiện hành.'));addSection_(x.body,'6. Bước tiếp theo',String(p.next_step||'Sunbot và Nhà trường xác nhận phạm vi đề xuất, sau đó hoàn thiện báo giá/hợp đồng nếu phù hợp.'));x.body.appendParagraph('TÀI LIỆU DỰ THẢO – CHỈ GỬI RA NGOÀI SAU KHI ĐƯỢC DUYỆT').setBold(true);const urls=saveDocPdf_(x.doc,ref),id=appendDocRecord_(user,c,'PROPOSAL',ref,'PENDING_APPROVAL',urls);return{ok:true,document_id:id,reference:ref,status:'PENDING_APPROVAL',doc_url:urls.doc_url,pdf_url:urls.pdf_url,message:'Đã tạo Proposal dự thảo và chuyển chờ duyệt.'};}
function documentApprove_(user,p){required_(p,['document_id']);const r=findOne_(DOC_ENGINE.SHEET,'document_id',p.document_id);if(!r)throw new Error('Không tìm thấy tài liệu.');const actor=roleClass_(user);if(actor!=='ADMIN'&&actor!=='LEADER')throw new Error('Bạn không có quyền duyệt proposal.');if(actor==='LEADER'){const creatorClass=roleClass_(String(r.created_by_user_id));if(creatorClass!=='STAFF')throw new Error('Leader chỉ duyệt proposal do Staff tạo.');}updateById_(DOC_ENGINE.SHEET,'document_id',r.document_id,{status:'APPROVED',approval_note:String(p.note||''),approved_by_user_id:user.user_id,approved_at:now_(),updated_at:now_()});audit_(user,'APPROVE_DOCUMENT',DOC_ENGINE.SHEET,r.document_id,{type:r.document_type});return{ok:true,message:'Đã duyệt tài liệu.'};}
function documentReject_(user,p){required_(p,['document_id']);const r=findOne_(DOC_ENGINE.SHEET,'document_id',p.document_id);if(!r)throw new Error('Không tìm thấy tài liệu.');if(!['ADMIN','LEADER'].includes(roleClass_(user)))throw new Error('Bạn không có quyền trả lại tài liệu.');updateById_(DOC_ENGINE.SHEET,'document_id',r.document_id,{status:'NEEDS_REVISION',approval_note:String(p.note||'Cần chỉnh sửa'),approved_by_user_id:user.user_id,approved_at:now_(),updated_at:now_()});audit_(user,'REJECT_DOCUMENT',DOC_ENGINE.SHEET,r.document_id,{note:p.note||''});return{ok:true,message:'Đã trả lại để chỉnh sửa.'};}
