const SALES_ADMIN = Object.freeze({
  ROLE_LEADER:'SALES_LEADER', ROLE_STAFF:'SALES_STAFF',
  CREDENTIAL_HEADERS:['user_id','email','login_id','visible_pin','verifier_hmac_sha256','status','updated_at'],
  DEFAULT_STAFF:[
    {user_id:'STAFF-01',login_id:'staff1',name:'Staff 1'},
    {user_id:'STAFF-02',login_id:'staff2',name:'Staff 2'},
    {user_id:'STAFF-03',login_id:'staff3',name:'Staff 3'}
  ]
});
function apiSessionSalesAdmin(sessionToken, action, payload){const user=authenticateSession_(sessionToken);payload=payload||{};ensureSalesAdminRuntime_();switch(String(action||'')){case'bootstrap':return salesAdminBootstrap_(user);case'listUsers':return salesAdminListUsers_(user);case'saveUser':return salesAdminSaveUser_(user,payload);case'resetPin':return salesAdminResetPin_(user,payload);case'setActive':return salesAdminSetActive_(user,payload);case'assignablePeople':return salesAssignablePeople_(user);case'accessRows':return salesAdminAccessibleRows_(user);default:throw new Error('Tác vụ quản trị sale không hợp lệ.');}}
function ensureSalesAdminRuntime_(){
  ensureRoleRow_(SALES_ADMIN.ROLE_LEADER,'Leader phát triển trường','Có thể thêm trường, quản lý cơ hội và giao trường cho staff.');
  ensureRoleRow_(SALES_ADMIN.ROLE_STAFF,'Staff phát triển trường','Giáo viên/CTV được giao cơ hội và làm việc trên các trường của mình.');
  ['dashboard.view','update.create','task.view','account.view','weekly.view','weekly.submit'].forEach(function(p){ensureRolePerm_(SALES_ADMIN.ROLE_STAFF,p);ensureRolePerm_(SALES_ADMIN.ROLE_LEADER,p);});
  const roleRows=getAll_(APP.SHEETS.USER_ROLES),people=getAll_(APP.SHEETS.PEOPLE);
  people.filter(function(p){return isActiveStatus_(p.trang_thai);}).forEach(function(p){const roles=roleRows.filter(function(r){return String(r.user_id)===String(p.user_id)&&!r.valid_to;}).map(function(r){return String(r.role_code);});if(roles.some(function(r){return ['REGION_LEAD','MARKET','SALE_OPS'].includes(r);})&&!roles.includes('CEO')&&!roles.includes('ADMIN'))ensureUserRole_(p.user_id,SALES_ADMIN.ROLE_LEADER);});
  ensureOutreachDelegationColumn_();ensureCredentialSchema_();
  SALES_ADMIN.DEFAULT_STAFF.forEach(function(seed){let p=findOne_(APP.SHEETS.PEOPLE,'user_id',seed.user_id);if(!p)append_(APP.SHEETS.PEOPLE,{user_id:seed.user_id,ho_ten:seed.name,email:'',dia_ban:'',trang_thai:'ACTIVE',quan_ly_email:'',created_at:now_(),updated_at:now_()});ensureUserRole_(seed.user_id,SALES_ADMIN.ROLE_STAFF);ensureCredentialIdentity_(seed.user_id,'',seed.login_id);});
}
function ensureOutreachDelegationColumn_(){const sh=getDb_().getSheetByName(OUTREACH.SHEET);if(!sh)return;const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);if(!h.includes('assigned_by_user_id'))sh.getRange(1,sh.getLastColumn()+1).setValue('assigned_by_user_id');}
function ensureRoleRow_(code,name,desc){if(!findOne_(APP.SHEETS.ROLES,'role_code',code))append_(APP.SHEETS.ROLES,{role_code:code,ten_vai_tro:name,mo_ta:desc,trang_thai:'ACTIVE'});}
function ensureRolePerm_(role,perm){if(!getAll_(APP.SHEETS.ROLE_PERMS).some(function(r){return String(r.role_code)===role&&String(r.permission_code)===perm;}))append_(APP.SHEETS.ROLE_PERMS,{role_code:role,permission_code:perm,allowed:'TRUE'});}
function ensureUserRole_(userId,role){if(!getAll_(APP.SHEETS.USER_ROLES).some(function(r){return String(r.user_id)===String(userId)&&String(r.role_code)===role&&!String(r.valid_to||'').trim();}))append_(APP.SHEETS.USER_ROLES,{user_id:userId,role_code:role,valid_from:dateOutreach_(new Date()),valid_to:''});}
function ensureCredentialSchema_(){const ss=getDb_();let sh=ss.getSheetByName(PASSWORD_AUTH.SHEET);if(!sh){sh=ss.insertSheet(PASSWORD_AUTH.SHEET);sh.appendRow(SALES_ADMIN.CREDENTIAL_HEADERS);sh.setFrozenRows(1);return sh;}const headers=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[];SALES_ADMIN.CREDENTIAL_HEADERS.forEach(function(h){if(!headers.includes(h))sh.getRange(1,sh.getLastColumn()+1).setValue(h);});return sh;}
function credentialSheetMap_(){const sh=ensureCredentialSchema_(),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),m={};h.forEach(function(x,i){m[x]=i+1;});return{sh:sh,h:h,m:m};}
function ensureCredentialIdentity_(userId,email,loginId){const c=credentialSheetMap_(),rows=c.sh.getLastRow()>1?c.sh.getRange(2,1,c.sh.getLastRow()-1,c.h.length).getValues():[],idx=rows.findIndex(function(r){return String(r[c.m.user_id-1]||'')===String(userId);}),identifier=String(loginId||userId).trim();if(idx<0){const row=new Array(c.h.length).fill('');row[c.m.user_id-1]=userId;row[c.m.email-1]=email||'';row[c.m.login_id-1]=identifier;row[c.m.status-1]='INACTIVE';row[c.m.updated_at-1]=now_();c.sh.appendRow(row);return;}const rn=idx+2;if(email!==undefined&&c.m.email)c.sh.getRange(rn,c.m.email).setValue(email||'');if(identifier&&c.m.login_id)c.sh.getRange(rn,c.m.login_id).setValue(identifier);}
function ensureCredentialRow_(userId,email,loginId,pin){ensureCredentialIdentity_(userId,email,loginId);const c=credentialSheetMap_(),rows=c.sh.getRange(2,1,c.sh.getLastRow()-1,c.h.length).getValues(),idx=rows.findIndex(function(r){return String(r[c.m.user_id-1]||'')===String(userId);});if(idx<0)return;const rn=idx+2,identifier=String(loginId||userId).trim();if(pin){c.sh.getRange(rn,c.m.visible_pin).setValue(String(pin));c.sh.getRange(rn,c.m.verifier_hmac_sha256).setValue(credentialVerifier_(identifier,String(pin)));c.sh.getRange(rn,c.m.status).setValue('ACTIVE');}c.sh.getRange(rn,c.m.updated_at).setValue(now_());}
function roleClass_(userOrId){const id=typeof userOrId==='string'?userOrId:userOrId.user_id,roles=activeRolesForUser_(id).map(String);if(roles.includes('ADMIN')||roles.includes('CEO'))return'ADMIN';if(roles.includes(SALES_ADMIN.ROLE_LEADER)||roles.includes('REGION_LEAD'))return'LEADER';if(roles.includes(SALES_ADMIN.ROLE_STAFF))return'STAFF';return'OTHER';}
function requireAdminUser_(user){if(roleClass_(user)!=='ADMIN')throw new Error('Chỉ Admin/CEO được quản trị người dùng.');}
function canAssignTo_(actor,targetId){const a=roleClass_(actor),t=roleClass_(targetId);if(a==='ADMIN')return t==='LEADER'||t==='STAFF';if(a==='LEADER')return String(targetId)===String(actor.user_id)||t==='STAFF';if(a==='STAFF')return String(targetId)===String(actor.user_id);return false;}
function salesCanAccessRow_(user,row){const c=roleClass_(user);if(c==='ADMIN')return true;if(String(row.owner_user_id)===String(user.user_id))return true;if(c==='LEADER'&&roleClass_(String(row.owner_user_id))==='STAFF'&&String(row.assigned_by_user_id||'')===String(user.user_id))return true;return false;}
function salesAssignablePeople_(user){const people=getAll_(APP.SHEETS.PEOPLE).filter(function(p){return isActiveStatus_(p.trang_thai)&&canAssignTo_(user,p.user_id);}).map(function(p){return{user_id:String(p.user_id),ho_ten:String(p.ho_ten||p.user_id),email:String(p.email||''),role_class:roleClass_(p.user_id)};});return{people:people.sort(function(a,b){return a.ho_ten.localeCompare(b.ho_ten,'vi');}),actor_role:roleClass_(user)};}
function salesAdminAccessibleRows_(user){const people={};getAll_(APP.SHEETS.PEOPLE).forEach(function(p){people[String(p.user_id)]={name:String(p.ho_ten||p.user_id),role:roleClass_(p.user_id)};});const rows=getAll_(OUTREACH.SHEET).filter(function(r){return salesCanAccessRow_(user,r);}).map(function(r){const x=Object.assign({},r);x.owner_name=(people[String(r.owner_user_id)]||{}).name||String(r.owner_user_id||'');x.owner_role=(people[String(r.owner_user_id)]||{}).role||'';return x;});return{rows:rows,summary:outreachSummaryFromRows_(rows),generated_at:now_()};}
function salesAdminBootstrap_(user){return{role_class:roleClass_(user),can_manage_users:roleClass_(user)==='ADMIN',assignable:salesAssignablePeople_(user).people};}
function salesAdminListUsers_(user){requireAdminUser_(user);const c=credentialSheetMap_(),creds={};if(c.sh.getLastRow()>1)c.sh.getRange(2,1,c.sh.getLastRow()-1,c.h.length).getValues().forEach(function(r){const o={};c.h.forEach(function(h,i){o[h]=r[i];});if(o.user_id)creds[String(o.user_id)]=o;});return getAll_(APP.SHEETS.PEOPLE).filter(function(p){return p.user_id;}).map(function(p){const cr=creds[String(p.user_id)]||{};return{user_id:String(p.user_id),ho_ten:String(p.ho_ten||''),email:String(p.email||''),dia_ban:String(p.dia_ban||''),trang_thai:String(p.trang_thai||''),role_class:roleClass_(p.user_id),login_id:String(cr.login_id||cr.email||p.email||p.user_id),visible_pin:String(cr.visible_pin||'')};});}
function salesAdminSaveUser_(user,p){requireAdminUser_(user);required_(p,['ho_ten','login_id','role_class']);const role=String(p.role_class||'STAFF').toUpperCase();if(!['LEADER','STAFF'].includes(role))throw new Error('Vai trò chỉ có thể là Leader hoặc Staff.');const login=String(p.login_id||'').trim();if(!/^[A-Za-z0-9._@-]{3,80}$/.test(login))throw new Error('ID đăng nhập không hợp lệ.');let id=String(p.user_id||'').trim();const isNew=!id;if(isNew)id='USR-'+Utilities.getUuid().slice(0,8).toUpperCase();const email=String(p.email||'').trim().toLowerCase();if(email&&!isPlainEmail_(email))throw new Error('Email không hợp lệ.');const old=findOne_(APP.SHEETS.PEOPLE,'user_id',id);if(old)updateById_(APP.SHEETS.PEOPLE,'user_id',id,{ho_ten:String(p.ho_ten).trim(),email:email,dia_ban:String(p.dia_ban||''),trang_thai:'ACTIVE',updated_at:now_()});else append_(APP.SHEETS.PEOPLE,{user_id:id,ho_ten:String(p.ho_ten).trim(),email:email,dia_ban:String(p.dia_ban||''),trang_thai:'ACTIVE',quan_ly_email:'',created_at:now_(),updated_at:now_()});ensureUserRole_(id,role==='LEADER'?SALES_ADMIN.ROLE_LEADER:SALES_ADMIN.ROLE_STAFF);const pin=String(p.pin||'').trim();if(isNew&&!/^\d{6}$/.test(pin))throw new Error('User mới cần mật khẩu PIN 6 số.');ensureCredentialRow_(id,email,login,pin||undefined);audit_(user,isNew?'CREATE_USER':'UPDATE_USER','NHAN_SU',id,{role:role,login_id:login});return{ok:true,user_id:id,message:isNew?'Đã thêm người dùng.':'Đã cập nhật người dùng.'};}
function salesAdminResetPin_(user,p){requireAdminUser_(user);required_(p,['user_id','new_pin']);const pin=String(p.new_pin||'');if(!/^\d{6}$/.test(pin))throw new Error('PIN phải gồm 6 số.');const person=findOne_(APP.SHEETS.PEOPLE,'user_id',p.user_id);if(!person)throw new Error('Không tìm thấy user.');const c=credentialSheetMap_(),rows=c.sh.getLastRow()>1?c.sh.getRange(2,1,c.sh.getLastRow()-1,c.h.length).getValues():[],i=rows.findIndex(function(r){return String(r[c.m.user_id-1])===String(p.user_id);});if(i<0)throw new Error('User chưa có credential.');const rn=i+2,login=String(rows[i][c.m.login_id-1]||rows[i][c.m.email-1]||p.user_id);c.sh.getRange(rn,c.m.visible_pin).setValue(pin);c.sh.getRange(rn,c.m.verifier_hmac_sha256).setValue(credentialVerifier_(login,pin));c.sh.getRange(rn,c.m.status).setValue('ACTIVE');c.sh.getRange(rn,c.m.updated_at).setValue(now_());audit_(user,'RESET_PIN','AUTH_CREDENTIALS',p.user_id,{});return{ok:true,message:'Đã reset PIN.'};}
function salesAdminSetActive_(user,p){requireAdminUser_(user);required_(p,['user_id']);const active=!!p.active;if(String(p.user_id)===String(user.user_id)&&!active)throw new Error('Không thể khóa chính tài khoản đang dùng.');updateById_(APP.SHEETS.PEOPLE,'user_id',p.user_id,{trang_thai:active?'ACTIVE':'INACTIVE',updated_at:now_()});const c=credentialSheetMap_(),rows=c.sh.getLastRow()>1?c.sh.getRange(2,1,c.sh.getLastRow()-1,c.h.length).getValues():[],i=rows.findIndex(function(r){return String(r[c.m.user_id-1])===String(p.user_id);});if(i>=0)c.sh.getRange(i+2,c.m.status).setValue(active?'ACTIVE':'INACTIVE');audit_(user,active?'RESTORE_USER':'SOFT_DELETE_USER','NHAN_SU',p.user_id,{});return{ok:true};}
