// School OS V2 migration — lineage-safe revision 2026-09-13
// Nguồn chính: 7.9_SUNBOT_SCHOOL_OS_PRODUCTION. Archive/source cũ chỉ dùng làm evidence.
// Nguyên tắc: lịch sử gắn với pháp nhân phát sinh; successor đọc predecessor qua SCHOOL_LINEAGE.
// Không tự tạo Opportunity. Không tạo artificial overdue queue. Không ghi đè nghiên cứu hiện hành.
const SO_V2_MIGRATION_20260912=Object.freeze({
  SOURCE_ID:'1alKUr9W3I-kKEyuTZOmDLCY8ZV1go49N0Q9HzpicnZI',
  LEGACY_REFERENCE_ID:'1EB-nbVGV38tfYRRla2t_9FmGP51UZo7dbkC_sOSXb-A',
  TARGET_ID:'19UA9f8R5onFTHc77cPIYxIyG2a6ugytpvwi8Y0l0Xf8',
  VERSION:'2026.09.13-migration-v2-lineage-safe',
  MIGRATION_DATE:'2026-09-13',
  USER_MAP:Object.freeze({USR0001:'U-CEO',USR0002:'U-NHUNG',USR0003:'U-DUNG',USR0004:'U-THU'}),
  LINEAGE_ROLLUP_STATUS:Object.freeze({CONFIRMED:true,CONFIRMED_WITH_SOURCE_CONFLICT:true})
});
function svmRows_(ssId,name){const sh=SpreadsheetApp.openById(ssId).getSheetByName(name);if(!sh)return[];const v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(x=>String(x||'').trim());return v.slice(1).filter(r=>r.some(x=>String(x==null?'':x).trim()!=='')).map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>{if(k)o[k]=r[j]});return o})}
function svmTarget_(){return SpreadsheetApp.openById(SO_V2_MIGRATION_20260912.TARGET_ID)}
function svmNorm_(v){return String(v||'').normalize('NFKC').trim().toLocaleLowerCase('vi-VN').replace(/\s+/g,' ')}
function svmTruthy_(v){return v===true||String(v).toUpperCase()==='TRUE'||String(v)==='1'}
function svmId_(prefix,text){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,String(text||''),Utilities.Charset.UTF_8);return prefix+'-'+b.map(x=>('0'+((x<0?x+256:x).toString(16))).slice(-2)).join('').slice(0,12).toUpperCase()}
function svmEnsureSheet_(name,headers){const ss=svmTarget_();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getMaxColumns()<headers.length)sh.insertColumnsAfter(sh.getMaxColumns(),headers.length-sh.getMaxColumns());const last=sh.getLastColumn(),current=last?sh.getRange(1,1,1,last).getDisplayValues()[0].map(String):[];if(!current.some(Boolean))sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);return sh}
function svmHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(String)}
function svmUpsert_(sh,headers,idField,id,record){const lastRow=sh.getLastRow(),h=headers&&headers.length?headers:svmHeaders_(sh),idCol=h.indexOf(idField);if(idCol<0)throw new Error('Thiếu cột '+idField+' ở '+sh.getName());let row=0;if(lastRow>=2){const ids=sh.getRange(2,idCol+1,lastRow-1,1).getDisplayValues();for(let i=0;i<ids.length;i++)if(String(ids[i][0])===String(id)){row=i+2;break}}const arr=h.map(k=>record[k]===undefined?'':record[k]);if(row)sh.getRange(row,1,1,h.length).setValues([arr]);else sh.appendRow(arr)}
function svmOwner_(r){const direct=SO_V2_MIGRATION_20260912.USER_MAP[String(r.owner_user_id||'')];if(direct)return direct;const n=svmNorm_(r.owner||r.actor||r.created_by);if(n.indexOf('nhung')>=0)return'U-NHUNG';if(n.indexOf('dung')>=0)return'U-DUNG';if(n.indexOf('thu')>=0)return'U-THU';return'U-CEO'}
function svmStatus_(r){const s=svmNorm_(r.status),note=svmNorm_(r.profile_note||'');if(note.indexOf('bỏ, bị sát nhập')>=0||s.indexOf('đã chuyển đầu mối')>=0)return'CLOSED';if(s.indexOf('đang triển khai')>=0)return'CUSTOMER';if(s.indexOf('có tín hiệu')>=0||s.indexOf('tái kích hoạt')>=0)return'ENGAGED';if(s.indexOf('theo dõi')>=0)return'NURTURE';if(s.indexOf('chờ phản hồi')>=0||s.indexOf('kênh tiếp cận')>=0)return'CONTACTED';return'TARGET'}
function svmSchoolMaps_(){const target=svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,'SCHOOLS'),byName={},bySource={},byId={};target.forEach(r=>{const id=String(r.school_id||'');if(!id)return;byId[id]=id;if(r.school_name&&!byName[svmNorm_(r.school_name)])byName[svmNorm_(r.school_name)]=id});svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,'MIGRATION_MAP').forEach(r=>{if(r.source_school_id&&r.v2_school_id)bySource[String(r.source_school_id)]=String(r.v2_school_id)});return{byName,bySource,byId}}
function svmResolveSourceSchool_(r,maps){const sourceId=String(r.school_id||'').trim();if(sourceId&&maps.byId[sourceId])return maps.byId[sourceId];if(sourceId&&maps.bySource[sourceId])return maps.bySource[sourceId];const byName=maps.byName[svmNorm_(r.school_name)];return byName||''}
function svmLineageIndex_(){const byLegacy={},predecessors={};svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,'SCHOOL_LINEAGE').forEach(r=>{const legacy=String(r.legacy_school_id||''),current=String(r.current_school_id||''),status=String(r.status||'').toUpperCase();if(legacy)byLegacy[legacy]=r;if(current&&legacy&&SO_V2_MIGRATION_20260912.LINEAGE_ROLLUP_STATUS[status]){if(!predecessors[current])predecessors[current]=[];predecessors[current].push(legacy)}});return{byLegacy,predecessors}}
function svmGenericContact_(r){const n=svmNorm_(r.name);return !n||n==='bgh / đầu mối chưa xác định'||n==='bgh/đầu mối chưa xác định'||n==='chưa xác định'}
function svmContactRecord_(r,sid,now){if(svmGenericContact_(r))return null;const id='MIG-'+String(r.contact_id||svmId_('CON',String(r.school_id||'')+'|'+String(r.name||'')+'|'+String(r.phone||'')));return{contact_id:id,school_id:sid,name:String(r.name||''),role:String(r.role||''),decision_role:String(r.decision_role||''),email:String(r.email||''),phone:String(r.phone||''),sentiment:String(r.sentiment||''),status:'HISTORICAL',source:'MIGRATED_7_9:'+String(r.contact_id||''),source_updated_at:String(r.updated_at||''),created_at:String(r.updated_at||now),updated_at:now}}
function svmActivityFingerprint_(r){let detail=String(r.detail_json||'');try{const j=JSON.parse(detail);delete j.han;detail=JSON.stringify(j)}catch(e){}return svmNorm_([r.school_id,r.event_type,r.actor,r.summary,detail].join('|'))}
function svmDueDate_(v){if(!v)return'';try{return Utilities.formatDate(new Date(v),'Asia/Ho_Chi_Minh','yyyy-MM-dd')}catch(e){return String(v).slice(0,10)}}
function svmTaskStatus_(r){if(svmTruthy_(r.done))return'DONE';const due=svmDueDate_(r.due);return due&&due>=SO_V2_MIGRATION_20260912.MIGRATION_DATE?'OPEN':'SUPERSEDED'}
function svmPreview20260912(){return svmPreview20260913()}
function svmPreview20260913(){const names=['SO_SCHOOLS','SO_CONTACTS','SO_TASKS','SO_ACTIVITIES','SO_TRACKED_LINKS','SO_OPPORTUNITIES','SO_SCHOOL_PROPOSALS'],source={};names.forEach(n=>source[n]=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,n).length);const target={};['SCHOOLS','CONTACTS','SCHOOL_INTELLIGENCE','INTERACTIONS','NEXT_ACTIONS','DOCUMENTS','SCHOOL_LINEAGE'].forEach(n=>target[n]=svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,n).length);const maps=svmSchoolMaps_(),unmapped={contacts:0,activities:0,tasks:0,documents:0};[['SO_CONTACTS','contacts'],['SO_ACTIVITIES','activities'],['SO_TASKS','tasks'],['SO_TRACKED_LINKS','documents']].forEach(x=>svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,x[0]).forEach(r=>{if(!svmResolveSourceSchool_(r,maps))unmapped[x[1]]++}));const contacts=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_CONTACTS');return{version:SO_V2_MIGRATION_20260912.VERSION,source,target,unmapped,generic_contacts_not_promoted:contacts.filter(svmGenericContact_).length,named_contacts_candidate:contacts.filter(r=>!svmGenericContact_(r)&&!String(r.deleted_at||'').trim()).length,policy:'History keeps legacy school_id. Current-school detail rolls up confirmed predecessors. No auto Opportunity. Stale unfinished legacy tasks become SUPERSEDED.'}}
function svmRun20260912(options){return svmRun20260913(options)}
function svmRun20260913(options){options=options||{};const historyOnly=options.historyOnly!==false,lock=LockService.getScriptLock();lock.waitLock(30000);try{const now=new Date().toISOString(),maps=svmSchoolMaps_(),lineage=svmLineageIndex_();const mapH=['source_system','source_school_id','source_school_name','v2_school_id','mapping_basis','lineage_current_school_id','migration_version','migrated_at'];const mapSh=svmEnsureSheet_('MIGRATION_MAP',mapH),mapHeaders=svmHeaders_(mapSh);let mappedSchools=0,unmappedSchools=0;
  svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_SCHOOLS').forEach(r=>{if(String(r.deleted_at||'').trim())return;const sourceId=String(r.school_id||'').trim(),sid=svmResolveSourceSchool_(r,maps);if(!sid){unmappedSchools++;return}const lin=lineage.byLegacy[sourceId]||{};svmUpsert_(mapSh,mapHeaders,'source_school_id',sourceId,{source_system:'7.9_SUNBOT_SCHOOL_OS_PRODUCTION',source_school_id:sourceId,source_school_name:String(r.school_name||''),v2_school_id:sid,mapping_basis:maps.byId[sourceId]?'EXACT_LEGACY_ID':maps.bySource[sourceId]?'EXISTING_MAP':'EXACT_NORMALIZED_NAME',lineage_current_school_id:String(lin.current_school_id||''),migration_version:SO_V2_MIGRATION_20260912.VERSION,migrated_at:now});mappedSchools++});
  if(!historyOnly){const schoolsSh=svmTarget_().getSheetByName('SCHOOLS');if(!schoolsSh)throw new Error('Thiếu SCHOOLS ở V2.');const h=svmHeaders_(schoolsSh);svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_SCHOOLS').forEach(r=>{if(String(r.deleted_at||'').trim())return;const sid=svmResolveSourceSchool_(r,maps);if(!sid)return;const lin=lineage.byLegacy[String(r.school_id||'')];if(lin&&SO_V2_MIGRATION_20260912.LINEAGE_ROLLUP_STATUS[String(lin.status||'').toUpperCase()])return;svmUpsert_(schoolsSh,h,'school_id',sid,{school_id:sid,school_name:String(r.school_name||''),school_type:String(r.school_type||''),province:String(r.region||''),district:'',address:String(r.address||''),website:String(r.website_url||''),contact_name:String(r['Tên Hiệu trưởng']||''),contact_role:String(r['Tên Hiệu trưởng']?'Hiệu trưởng':''),contact_email:String(r.school_email||''),contact_phone:String(r['ĐT/ FB Hiệu trưởng']||r.hotline||r.Hotline||''),current_owner_id:svmOwner_(r),leader_id:svmOwner_(r),relationship_state:svmStatus_(r),source:'MIGRATED_7_9',active:true,created_at:String(r.updated_at||now),updated_at:now})})}
  const contactSh=svmTarget_().getSheetByName('CONTACTS');if(!contactSh)throw new Error('Thiếu CONTACTS ở V2.');const contactH=svmHeaders_(contactSh);let contacts=0,contactPlaceholders=0,unmappedContacts=0;svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_CONTACTS').forEach(r=>{if(String(r.deleted_at||'').trim())return;const sid=svmResolveSourceSchool_(r,maps);if(!sid){unmappedContacts++;return}const rec=svmContactRecord_(r,sid,now);if(!rec){contactPlaceholders++;return}svmUpsert_(contactSh,contactH,'contact_id',rec.contact_id,rec);contacts++});
  const intSh=svmTarget_().getSheetByName('INTERACTIONS');if(!intSh)throw new Error('Thiếu INTERACTIONS ở V2.');const intH=svmHeaders_(intSh),seen={},sourceActs=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_ACTIVITIES').slice().sort((a,b)=>String(a.timestamp||'').localeCompare(String(b.timestamp||'')));let interactions=0,dedupedActivities=0,unmappedActivities=0;sourceActs.forEach(r=>{const sid=svmResolveSourceSchool_(r,maps);if(!sid){unmappedActivities++;return}const fp=svmActivityFingerprint_(r),t=new Date(r.timestamp||0).getTime(),prev=seen[fp];if(prev&&Math.abs(t-prev)<60000){dedupedActivities++;return}seen[fp]=t;const id='MIG-'+String(r.event_id||svmId_('EV',sid+'|'+String(r.timestamp||'')+'|'+fp));svmUpsert_(intSh,intH,'interaction_id',id,{interaction_id:id,school_id:sid,opportunity_id:'',interaction_type:String(r.event_type||'LEGACY_ACTIVITY'),interaction_at:String(r.timestamp||now),summary:String(r.summary||r.event_type||''),result:String(r.detail_json||''),created_by:svmOwner_({owner:r.actor}),created_at:String(r.timestamp||now)});interactions++});
  const actSh=svmTarget_().getSheetByName('NEXT_ACTIONS');if(!actSh)throw new Error('Thiếu NEXT_ACTIONS ở V2.');const actH=svmHeaders_(actSh),openCandidate={};const tasks=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_TASKS').filter(r=>!String(r.deleted_at||'').trim());tasks.forEach(r=>{if(svmTaskStatus_(r)!=='OPEN')return;const sid=svmResolveSourceSchool_(r,maps);if(!sid)return;const old=openCandidate[sid],due=svmDueDate_(r.due);if(!old||due<String(old._due||'9999-12-31'))openCandidate[sid]=Object.assign({_due:due},r)});let actions=0,openActions=0,unmappedTasks=0;tasks.forEach(r=>{const sid=svmResolveSourceSchool_(r,maps);if(!sid){unmappedTasks++;return}let status=svmTaskStatus_(r);if(status==='OPEN'&&openCandidate[sid]!==r)status='SUPERSEDED';if(status==='OPEN')openActions++;const id='MIG-'+String(r.task_id||svmId_('ACT',sid+'|'+String(r.title||'')));svmUpsert_(actSh,actH,'action_id',id,{action_id:id,school_id:sid,opportunity_id:'',owner_id:svmOwner_(r),action_text:String(r.title||''),due_date:svmDueDate_(r.due),status:status,priority:svmNorm_(r.risk).indexOf('cao')>=0?'P1':'P2',completed_at:svmTruthy_(r.done)?String(r.updated_at||''):'',created_by:svmOwner_(r),created_at:String(r.updated_at||now),updated_at:now});actions++});
  const docSh=svmTarget_().getSheetByName('DOCUMENTS');if(!docSh)throw new Error('Thiếu DOCUMENTS ở V2.');const docH=svmHeaders_(docSh);let documents=0,unmappedDocuments=0;svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_TRACKED_LINKS').forEach(r=>{const sid=svmResolveSourceSchool_(r,maps);if(!sid){unmappedDocuments++;return}const id='MIG-'+String(r.link_id||svmId_('DOC',sid+'|'+String(r.public_code||r.url||r.target_url||'')));svmUpsert_(docSh,docH,'document_id',id,{document_id:id,school_id:sid,opportunity_id:'',document_type:'TRACKED_LINK',title:String(r.asset_type||r.public_code||'Hồ sơ điện tử'),url:String(r.url||r.target_url||''),status:'MIGRATED',created_by:svmOwner_({owner:r.created_by||r.owner}),created_at:String(r.created_at||now),updated_at:now});documents++});
  const settings=svmTarget_().getSheetByName('SETTINGS');if(settings){const h=svmHeaders_(settings);if(h.indexOf('key')>=0)svmUpsert_(settings,h,'key','migration_20260913',{key:'migration_20260913',value:SO_V2_MIGRATION_20260912.VERSION,updated_at:now})}
  return{ok:true,version:SO_V2_MIGRATION_20260912.VERSION,history_only:historyOnly,mapped_schools:mappedSchools,unmapped_schools:unmappedSchools,contacts_imported:contacts,contact_placeholders_not_promoted:contactPlaceholders,interactions_imported:interactions,duplicate_activities_suppressed:dedupedActivities,actions_imported:actions,open_actions:openActions,documents_imported:documents,unmapped:{contacts:unmappedContacts,activities:unmappedActivities,tasks:unmappedTasks,documents:unmappedDocuments},opportunities_created:0};
 }finally{lock.releaseLock()}}
