// School OS V2 migration — 2026-09-12
// Nguồn chính: 7.9_SUNBOT_SCHOOL_OS_PRODUCTION. Nguồn cũ SUNBOT_SCHOOL_OS_PRODUCTION chỉ đối chiếu.
// Không tự tạo Opportunity từ dữ liệu cũ; giữ Discovery/Opportunity gate của V2.
const SO_V2_MIGRATION_20260912=Object.freeze({
  SOURCE_ID:'1alKUr9W3I-kKEyuTZOmDLCY8ZV1go49N0Q9HzpicnZI',
  LEGACY_REFERENCE_ID:'1EB-nbVGV38tfYRRla2t_9FmGP51UZo7dbkC_sOSXb-A',
  TARGET_ID:'19UA9f8R5onFTHc77cPIYxIyG2a6ugytpvwi8Y0l0Xf8',
  VERSION:'2026.09.12-migration-v1',
  USER_MAP:Object.freeze({USR0001:'U-CEO',USR0002:'U-NHUNG',USR0003:'U-DUNG',USR0004:'U-THU'})
});
function svmRows_(ssId,name){const sh=SpreadsheetApp.openById(ssId).getSheetByName(name);if(!sh)return[];const v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(x=>String(x||'').trim());return v.slice(1).filter(r=>r.some(x=>String(x==null?'':x).trim()!=='' )).map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>{if(k)o[k]=r[j]});return o})}
function svmTarget_(){return SpreadsheetApp.openById(SO_V2_MIGRATION_20260912.TARGET_ID)}
function svmNorm_(v){return String(v||'').normalize('NFKC').trim().toLocaleLowerCase('vi-VN').replace(/\s+/g,' ')}
function svmTruthy_(v){return v===true||String(v).toUpperCase()==='TRUE'||String(v)==='1'}
function svmId_(prefix,text){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,String(text||''),Utilities.Charset.UTF_8);return prefix+'-'+b.map(x=>('0'+((x<0?x+256:x).toString(16))).slice(-2)).join('').slice(0,12).toUpperCase()}
function svmEnsureSheet_(name,headers){const ss=svmTarget_();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getMaxColumns()<headers.length)sh.insertColumnsAfter(sh.getMaxColumns(),headers.length-sh.getMaxColumns());sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);return sh}
function svmTable_(name,headers){const sh=svmEnsureSheet_(name,headers),last=sh.getLastRow();if(last<2)return{sh,headers,rows:[],byId:{}};const vals=sh.getRange(1,1,last,headers.length).getValues(),h=vals[0].map(String),rows=vals.slice(1).filter(r=>r.some(x=>String(x||'').trim())).map((r,i)=>{const o={_row:i+2};h.forEach((k,j)=>o[k]=r[j]);return o}),byId={};return{sh,headers:h,rows,byId}}
function svmUpsert_(sh,headers,idField,id,record){const vals=sh.getDataRange().getValues(),h=vals.length?vals[0].map(String):headers,idCol=h.indexOf(idField);let row=0;for(let i=1;i<vals.length;i++)if(String(vals[i][idCol])===String(id)){row=i+1;break}const arr=h.map(k=>record[k]===undefined?'':record[k]);if(row)sh.getRange(row,1,1,h.length).setValues([arr]);else sh.appendRow(arr)}
function svmStatus_(r){const s=String(r.status||'').toLowerCase(),note=String(r['profile_note \n1.Tình hình sau sát nhập tên mới, ghép với trường nào, ht là ai - số điện thoại, sĩ số 3-5 tuổi, chính? có sunbot chưa?\n2. Ghi nhận sau khai giảng: đối tác steam nào ko? đối tác quan trọng về dịch vụ nào? ']||r.profile_note||'').toLowerCase();if(note.indexOf('bỏ, bị sát nhập')>=0||s.indexOf('đã chuyển đầu mối')>=0)return'CLOSED';if(s.indexOf('đang triển khai')>=0)return'CUSTOMER';if(s.indexOf('có tín hiệu')>=0||s.indexOf('tái kích hoạt')>=0)return'ENGAGED';if(s.indexOf('theo dõi')>=0)return'NURTURE';if(s.indexOf('chờ phản hồi')>=0||s.indexOf('kênh tiếp cận')>=0)return'CONTACTED';return'TARGET'}
function svmOwner_(r){const direct=SO_V2_MIGRATION_20260912.USER_MAP[String(r.owner_user_id||'')];if(direct)return direct;const n=svmNorm_(r.owner);if(n.indexOf('nhung')>=0)return'U-NHUNG';if(n.indexOf('dung')>=0)return'U-DUNG';if(n.indexOf('thu')>=0)return'U-THU';return'U-CEO'}
function svmSchoolMaps_(){const target=svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,'SCHOOLS'),byName={},bySource={};target.forEach(r=>{byName[svmNorm_(r.school_name)]=r.school_id});const mapRows=svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,'MIGRATION_MAP');mapRows.forEach(r=>{if(r.source_school_id)bySource[String(r.source_school_id)]=String(r.v2_school_id)});return{byName,bySource}}
function svmPreview20260912(){const names=['SO_SCHOOLS','SO_CONTACTS','SO_TASKS','SO_ACTIVITIES','SO_TRACKED_LINKS','SO_OPPORTUNITIES','SO_SCHOOL_PROPOSALS'];const source={};names.forEach(n=>source[n]=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,n).length);const target={};['SCHOOLS','INTERACTIONS','NEXT_ACTIONS','DISCOVERIES','OPPORTUNITIES','PROPOSALS','DOCUMENTS'].forEach(n=>target[n]=svmRows_(SO_V2_MIGRATION_20260912.TARGET_ID,n).length);return{version:SO_V2_MIGRATION_20260912.VERSION,source,target,policy:'SO_OPPORTUNITIES trống/không đủ gate thì không tự tạo Opportunity; nghiên cứu được giữ riêng trong SCHOOL_INTELLIGENCE.'}}
function svmRun20260912(){
  const lock=LockService.getScriptLock();lock.waitLock(30000);try{
    const maps=svmSchoolMaps_(),now=new Date().toISOString();
    const schoolsSh=svmTarget_().getSheetByName('SCHOOLS');if(!schoolsSh)throw new Error('Thiếu SCHOOLS ở V2.');const schoolHeaders=schoolsSh.getRange(1,1,1,schoolsSh.getLastColumn()).getDisplayValues()[0].map(String);
    const mapH=['source_system','source_school_id','source_school_name','v2_school_id','migration_version','migrated_at'];const mapSh=svmEnsureSheet_('MIGRATION_MAP',mapH);
    const intelH=['intelligence_id','school_id','source_school_id','source_updated_at','steam_status','risk','profile_note','research_hotline','headmaster_name','headmaster_contact','enrollment_research','product_potential','source_owner','source_record_version','migration_version','updated_at'];const intelSh=svmEnsureSheet_('SCHOOL_INTELLIGENCE',intelH);
    const contactH=['contact_id','school_id','name','role','decision_role','email','phone','sentiment','status','source_contact_id','source_updated_at','migration_version','updated_at'];const contactSh=svmEnsureSheet_('CONTACTS',contactH);
    const sourceSchools=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_SCHOOLS');let schoolCount=0;
    sourceSchools.forEach(r=>{if(String(r.deleted_at||'').trim())return;const sourceId=String(r.school_id||'').trim(),name=String(r.school_name||'').trim();if(!name)return;let id=maps.bySource[sourceId]||maps.byName[svmNorm_(name)]||svmId_('SCH-MIG',sourceId||name);const owner=svmOwner_(r);const rec={school_id:id,school_name:name,school_type:String(r.school_type||''),province:String(r.region||''),district:'',address:String(r.address||''),website:String(r.website_url||''),contact_name:String(r['Tên Hiệu trưởng']||''),contact_role:String(r['Tên Hiệu trưởng']?'Hiệu trưởng':''),contact_email:String(r.school_email||''),contact_phone:String(r['ĐT/ FB Hiệu trưởng']||r.hotline||r.Hotline||''),current_owner_id:owner,leader_id:owner,relationship_state:svmStatus_(r),source:'MIGRATED_7_9',active:true,created_at:String(r.updated_at||now),updated_at:now};svmUpsert_(schoolsSh,schoolHeaders,'school_id',id,rec);svmUpsert_(mapSh,mapH,'source_school_id',sourceId||'NAME:'+svmNorm_(name),{source_system:'7.9_SUNBOT_SCHOOL_OS_PRODUCTION',source_school_id:sourceId||'NAME:'+svmNorm_(name),source_school_name:name,v2_school_id:id,migration_version:SO_V2_MIGRATION_20260912.VERSION,migrated_at:now});
      const profileKey=Object.keys(r).find(k=>k.indexOf('profile_note')===0)||'profile_note';const intelId=svmId_('INTEL',sourceId||name);svmUpsert_(intelSh,intelH,'intelligence_id',intelId,{intelligence_id:intelId,school_id:id,source_school_id:sourceId,source_updated_at:String(r.updated_at||''),steam_status:String(r.steam_status||''),risk:String(r.risk||''),profile_note:String(r[profileKey]||''),research_hotline:String(r.Hotline||r.hotline||''),headmaster_name:String(r['Tên Hiệu trưởng']||''),headmaster_contact:String(r['ĐT/ FB Hiệu trưởng']||''),enrollment_research:String(r['Sĩ số mới']||r.children||''),product_potential:String(r['Sản phẩm tiềm năng hoặc trao đổi riêng của sale']||''),source_owner:String(r.owner||''),source_record_version:String(r.record_version||''),migration_version:SO_V2_MIGRATION_20260912.VERSION,updated_at:now});schoolCount++});
    const freshMaps=svmSchoolMaps_();let contacts=0;svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_CONTACTS').forEach(r=>{if(String(r.deleted_at||'').trim())return;const sid=freshMaps.bySource[String(r.school_id||'')];if(!sid)return;const id='MIG-'+String(r.contact_id||svmId_('CON',sid+String(r.name||'')));svmUpsert_(contactSh,contactH,'contact_id',id,{contact_id:id,school_id:sid,name:String(r.name||''),role:String(r.role||''),decision_role:String(r.decision_role||''),email:String(r.email||''),phone:String(r.phone||''),sentiment:String(r.sentiment||''),status:String(r.status||'ACTIVE'),source_contact_id:String(r.contact_id||''),source_updated_at:String(r.updated_at||''),migration_version:SO_V2_MIGRATION_20260912.VERSION,updated_at:now});contacts++});
    const intSh=svmTarget_().getSheetByName('INTERACTIONS'),intH=intSh.getRange(1,1,1,intSh.getLastColumn()).getDisplayValues()[0].map(String);let interactions=0;svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_ACTIVITIES').forEach(r=>{const sid=freshMaps.bySource[String(r.school_id||'')];if(!sid)return;const id='MIG-'+String(r.event_id||svmId_('EV',sid+String(r.timestamp||'')));svmUpsert_(intSh,intH,'interaction_id',id,{interaction_id:id,school_id:sid,opportunity_id:'',interaction_type:String(r.event_type||'LEGACY_ACTIVITY'),interaction_at:String(r.timestamp||now),summary:String(r.summary||r.event_type||''),result:String(r.detail_json||''),created_by:svmOwner_({owner:r.actor}),created_at:String(r.timestamp||now)});interactions++});
    const actSh=svmTarget_().getSheetByName('NEXT_ACTIONS'),actH=actSh.getRange(1,1,1,actSh.getLastColumn()).getDisplayValues()[0].map(String);let actions=0;const tasks=svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_TASKS'),openBySchool={};tasks.filter(r=>!String(r.deleted_at||'').trim()&&!svmTruthy_(r.done)).forEach(r=>{const key=String(r.school_id||'');const old=openBySchool[key];if(!old||String(r.due||'')<String(old.due||''))openBySchool[key]=r});tasks.forEach(r=>{if(String(r.deleted_at||'').trim())return;const sid=freshMaps.bySource[String(r.school_id||'')];if(!sid)return;const id='MIG-'+String(r.task_id||svmId_('ACT',sid+String(r.title||''))),isOpen=openBySchool[String(r.school_id||'')]===r,status=svmTruthy_(r.done)?'DONE':isOpen?'OPEN':'SUPERSEDED';svmUpsert_(actSh,actH,'action_id',id,{action_id:id,school_id:sid,opportunity_id:'',owner_id:svmOwner_(r),action_text:String(r.title||''),due_date:r.due?Utilities.formatDate(new Date(r.due),'Asia/Ho_Chi_Minh','yyyy-MM-dd'):'',status:status,priority:String(r.risk||'').toLowerCase().indexOf('cao')>=0?'P1':'P2',completed_at:svmTruthy_(r.done)?String(r.updated_at||''):'',created_by:svmOwner_(r),created_at:String(r.updated_at||now),updated_at:now});actions++});
    const docSh=svmTarget_().getSheetByName('DOCUMENTS'),docH=docSh.getRange(1,1,1,docSh.getLastColumn()).getDisplayValues()[0].map(String);let documents=0;svmRows_(SO_V2_MIGRATION_20260912.SOURCE_ID,'SO_TRACKED_LINKS').forEach(r=>{const sid=freshMaps.bySource[String(r.school_id||'')];if(!sid)return;const id='MIG-'+String(r.link_id||svmId_('DOC',sid+String(r.public_code||'')));svmUpsert_(docSh,docH,'document_id',id,{document_id:id,school_id:sid,opportunity_id:'',document_type:'TRACKED_LINK',title:String(r.asset_type||r.public_code||'Hồ sơ điện tử'),url:String(r.url||r.target_url||''),status:'MIGRATED',created_by:svmOwner_({owner:r.created_by||r.owner}),created_at:String(r.created_at||now),updated_at:now});documents++});
    const settings=svmTarget_().getSheetByName('SETTINGS');if(settings){const h=settings.getRange(1,1,1,settings.getLastColumn()).getDisplayValues()[0].map(String);if(h.indexOf('key')>=0)svmUpsert_(settings,h,'key','migration_20260912',{key:'migration_20260912',value:SO_V2_MIGRATION_20260912.VERSION,updated_at:now})}
    return{ok:true,version:SO_V2_MIGRATION_20260912.VERSION,schools:schoolCount,contacts,interactions,actions,documents,opportunities_created:0};
  }finally{lock.releaseLock()}}
