// SUNBOT School OS V2 — Commercial Snapshot
// Admin locks a reviewed calculator state before any official document is generated.
const V2_COMMERCIAL=Object.freeze({SHEET:'COMMERCIAL_SNAPSHOTS',VERSION:'2026.09.12-v1'});
function v2CommercialSheet_(){const ss=v2Db_();let sh=ss.getSheetByName(V2_COMMERCIAL.SHEET);const h=['commercial_snapshot_id','proposal_snapshot_id','school_id','school_name','version','status','calculator_version','snapshot_json','summary_text','pricebook_version','locked_by','locked_at','created_at','updated_at'];if(!sh){sh=ss.insertSheet(V2_COMMERCIAL.SHEET);sh.getRange(1,1,1,h.length).setValues([h]);sh.setFrozenRows(1);}else{const current=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),1)).getDisplayValues()[0].map(String);h.forEach(function(x){if(current.indexOf(x)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(x);current.push(x);}});}return sh;}
function v2CommercialRows_(){v2CommercialSheet_();return v2Rows_(V2_COMMERCIAL.SHEET);}
function v2CommercialRequireAdmin_(u){if(String(u.role_code||'').toUpperCase()!=='ADMIN')throw new Error('Chỉ Admin được khóa phương án thương mại.');}
function v2CommercialView_(r){return {commercial_snapshot_id:r.commercial_snapshot_id,proposal_snapshot_id:r.proposal_snapshot_id,school_id:r.school_id,school_name:r.school_name,version:Number(r.version||1),status:r.status,calculator_version:r.calculator_version,summary_text:r.summary_text||'',pricebook_version:r.pricebook_version||'',locked_by:r.locked_by||'',locked_at:r.locked_at||'',created_at:r.created_at||'',updated_at:r.updated_at||''};}
function v2CommercialNextVersion_(schoolId){return v2CommercialRows_().filter(function(r){return String(r.school_id)===String(schoolId);}).length+1;}
function v2CommercialLock_(u,p){v2CommercialRequireAdmin_(u);p=p||{};const proposalId=String(p.proposal_snapshot_id||''),proposal=v2ProposalRows_().find(function(r){return String(r.proposal_snapshot_id)===proposalId;});if(!proposal)throw new Error('Không tìm thấy Proposal Snapshot nguồn.');const raw=p.snapshot;if(!raw||typeof raw!=='object')throw new Error('Chưa có Working Draft từ Máy tính.');const json=JSON.stringify(raw);if(json.length>45000)throw new Error('Working Draft quá lớn. Hãy tải lại Máy tính và thử lại.');const now=v2Now_(),id='CS-'+Utilities.getUuid().slice(0,8).toUpperCase(),version=v2CommercialNextVersion_(proposal.school_id);v2Append_(V2_COMMERCIAL.SHEET,{commercial_snapshot_id:id,proposal_snapshot_id:proposalId,school_id:proposal.school_id,school_name:proposal.school_name,version:version,status:'LOCKED',calculator_version:v2Clean_(p.calculator_version,80)||proposal.calculator_version||'deal-calculator-20260912',snapshot_json:json,summary_text:v2Clean_(p.summary_text,10000),pricebook_version:v2Clean_(p.pricebook_version,80)||'2026.09.12-v5',locked_by:u.user_id,locked_at:now,created_at:now,updated_at:now});v2UpdateById_(V2_PROPOSAL_SNAPSHOT.SHEET,'proposal_snapshot_id',proposalId,{status:'LOCKED',handled_by:u.user_id,handled_at:now,updated_at:now});v2Audit_('COMMERCIAL_SNAPSHOT',id,'LOCK','','',proposalId,u.user_id);v2Audit_('PROPOSAL_SNAPSHOT',proposalId,'STATUS','status',proposal.status,'LOCKED',u.user_id);return {ok:true,commercial_snapshot_id:id,proposal_snapshot_id:proposalId,school_id:proposal.school_id,school_name:proposal.school_name,version:version,status:'LOCKED'};}
function v2CommercialList_(u,p){v2CommercialRequireAdmin_(u);p=p||{};return v2CommercialRows_().filter(function(r){return !p.school_id||String(r.school_id)===String(p.school_id);}).sort(function(a,b){return String(b.locked_at||'').localeCompare(String(a.locked_at||''));}).map(v2CommercialView_);}
function v2CommercialDetail_(u,id){v2CommercialRequireAdmin_(u);const r=v2CommercialRows_().find(function(x){return String(x.commercial_snapshot_id)===String(id);});if(!r)throw new Error('Không tìm thấy Commercial Snapshot.');const out=v2CommercialView_(r);try{out.snapshot=JSON.parse(String(r.snapshot_json||'{}'));}catch(e){out.snapshot={};}return out;}
function apiSessionV2Commercial(sessionToken,action,payload){const u=v2RequireSession_(sessionToken),a=String(action||'');if(a==='lock')return v2CommercialLock_(u,payload||{});if(a==='list')return v2CommercialList_(u,payload||{});if(a==='detail')return v2CommercialDetail_(u,String((payload||{}).commercial_snapshot_id||''));throw new Error('Tác vụ Commercial Snapshot không hợp lệ.');}
