// SUNBOT School OS V2 — Document Release from locked Commercial Snapshot
// Official documents must originate from a locked Commercial Snapshot.
const V2_DOC_RELEASE=Object.freeze({
  SHEET:'DOCUMENTS',
  ROOT_NAME:'06_SCHOOL_OUTPUTS',
  SCHOOL_YEAR:'2026-2027',
  HEADERS:['document_id','school_id','commercial_snapshot_id','proposal_snapshot_id','document_type','document_name','version','status','folder_url','doc_url','pdf_url','created_by','created_at','updated_at']
});
function v2DocRequireAdmin_(u){if(String(u.role_code||'').toUpperCase()!=='ADMIN')throw new Error('Chỉ Admin được phát hành hồ sơ.');}
function v2DocSheet_(){const ss=v2Db_();let sh=ss.getSheetByName(V2_DOC_RELEASE.SHEET);if(!sh){sh=ss.insertSheet(V2_DOC_RELEASE.SHEET);sh.getRange(1,1,1,V2_DOC_RELEASE.HEADERS.length).setValues([V2_DOC_RELEASE.HEADERS]);sh.setFrozenRows(1);return sh;}let h=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getDisplayValues()[0].map(String);V2_DOC_RELEASE.HEADERS.forEach(function(x){if(h.indexOf(x)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(x);h.push(x);}});return sh;}
function v2DocRows_(){v2DocSheet_();return v2Rows_(V2_DOC_RELEASE.SHEET);}
function v2DocCommercial_(id){const r=v2CommercialRows_().find(function(x){return String(x.commercial_snapshot_id)===String(id);});if(!r)throw new Error('Không tìm thấy Commercial Snapshot.');if(String(r.status)!=='LOCKED')throw new Error('Chỉ Commercial Snapshot đã khóa mới được phát hành.');return r;}
function v2DocSchool_(schoolId){const r=v2Rows_(V2_OS.S.SCHOOLS).find(function(x){return String(x.school_id)===String(schoolId);});if(!r)throw new Error('Không tìm thấy hồ sơ trường.');return r;}
function v2DocSafeName_(s){return String(s||'').replace(/[\\/:*?"<>|#%{}]/g,' ').replace(/\s+/g,' ').trim().slice(0,120)||'TRUONG';}
function v2DocChild_(parent,name){const it=parent.getFoldersByName(name);return it.hasNext()?it.next():parent.createFolder(name);}
function v2DocFolder_(commercial){const root=DriveApp.getFolderById(PRODUCTION.ROOT_FOLDER_ID);const output=v2DocChild_(root,V2_DOC_RELEASE.ROOT_NAME);const school=v2DocChild_(output,v2DocSafeName_(commercial.school_name)+' · '+commercial.school_id);const year=v2DocChild_(school,V2_DOC_RELEASE.SCHOOL_YEAR);return v2DocChild_(year,'CS-'+String(commercial.version||1)+' · '+commercial.commercial_snapshot_id);}
function v2DocAppend_(u,c,type,name,folder,docUrl,pdfUrl){const now=v2Now_(),id='VDOC-'+Utilities.getUuid().slice(0,8).toUpperCase();v2Append_(V2_DOC_RELEASE.SHEET,{document_id:id,school_id:c.school_id,commercial_snapshot_id:c.commercial_snapshot_id,proposal_snapshot_id:c.proposal_snapshot_id,document_type:type,document_name:name,version:String(c.version||1),status:'READY',folder_url:folder.getUrl(),doc_url:docUrl||'',pdf_url:pdfUrl||'',created_by:u.user_id,created_at:now,updated_at:now});v2Audit_('DOCUMENT',id,'CREATE','commercial_snapshot_id','',c.commercial_snapshot_id,u.user_id);return id;}
function v2DocList_(u,p){v2DocRequireAdmin_(u);p=p||{};return v2DocRows_().filter(function(r){return !p.commercial_snapshot_id||String(r.commercial_snapshot_id)===String(p.commercial_snapshot_id);}).sort(function(a,b){return String(b.created_at||'').localeCompare(String(a.created_at||''));}).map(function(r){return {document_id:r.document_id,school_id:r.school_id,commercial_snapshot_id:r.commercial_snapshot_id,proposal_snapshot_id:r.proposal_snapshot_id,document_type:r.document_type,document_name:r.document_name,version:r.version,status:r.status,folder_url:r.folder_url,doc_url:r.doc_url,pdf_url:r.pdf_url,created_by:r.created_by,created_at:r.created_at};});}
function v2DocPrepare_(u,p){v2DocRequireAdmin_(u);const c=v2DocCommercial_(String((p||{}).commercial_snapshot_id||'')),folder=v2DocFolder_(c);return {ok:true,commercial_snapshot_id:c.commercial_snapshot_id,school_id:c.school_id,school_name:c.school_name,folder_url:folder.getUrl(),school_year:V2_DOC_RELEASE.SCHOOL_YEAR};}
function v2DocSummary_(u,p){v2DocRequireAdmin_(u);const c=v2DocCommercial_(String((p||{}).commercial_snapshot_id||''));const existing=v2DocRows_().find(function(r){return String(r.commercial_snapshot_id)===String(c.commercial_snapshot_id)&&String(r.document_type)==='PLAN_SUMMARY'&&String(r.status)==='READY';});if(existing)return {ok:true,reused:true,document_id:existing.document_id,doc_url:existing.doc_url,pdf_url:existing.pdf_url,folder_url:existing.folder_url};const school=v2DocSchool_(c.school_id),folder=v2DocFolder_(c),ref='SB-PA-'+Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyyMMdd')+'-'+Utilities.getUuid().slice(0,5).toUpperCase(),title='TÓM TẮT PHƯƠNG ÁN SUNBOT – '+c.school_name;const doc=DocumentApp.create(title),body=doc.getBody();body.appendParagraph('SUNBOT · KIRO VIỆT NAM').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('TÓM TẮT PHƯƠNG ÁN').setHeading(DocumentApp.ParagraphHeading.TITLE);const meta=body.appendTable([['Nhà trường',String(c.school_name||'')],['Mã phương án',String(c.commercial_snapshot_id)],['Phiên bản',String(c.version||1)],['Bảng giá',String(c.pricebook_version||'')],['Ngày khóa',String(c.locked_at||'').slice(0,10)]]);meta.setBorderWidth(0.5);body.appendHorizontalRule();body.appendParagraph('Phương án đã chốt').setHeading(DocumentApp.ParagraphHeading.HEADING2);String(c.summary_text||'Chưa có nội dung tóm tắt.').split('\n').filter(Boolean).forEach(function(line){body.appendParagraph(line);});body.appendParagraph('Thông tin trường').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('Loại hình: '+String(school.school_type||'')+'\nĐịa bàn: '+[school.district,school.province].filter(Boolean).join(', ')+'\nĐầu mối: '+String(school.contact_name||'')+(school.contact_role?' · '+school.contact_role:''));body.appendParagraph('Tài liệu được sinh từ Commercial Snapshot đã khóa. Mọi thay đổi thương mại cần tạo phiên bản Commercial Snapshot mới.').setItalic(true);doc.saveAndClose();const f=DriveApp.getFileById(doc.getId());f.setName(ref+' · Tóm tắt phương án · '+v2DocSafeName_(c.school_name));f.moveTo(folder);const pdf=folder.createFile(f.getAs(MimeType.PDF).setName(ref+' · Tóm tắt phương án · '+v2DocSafeName_(c.school_name)+'.pdf'));const id=v2DocAppend_(u,c,'PLAN_SUMMARY','Tóm tắt phương án',folder,f.getUrl(),pdf.getUrl());return {ok:true,reused:false,document_id:id,doc_url:f.getUrl(),pdf_url:pdf.getUrl(),folder_url:folder.getUrl(),reference:ref};}
function apiSessionV2Documents(sessionToken,action,payload){const u=v2RequireSession_(sessionToken),a=String(action||'');if(a==='list')return v2DocList_(u,payload||{});if(a==='prepare')return v2DocPrepare_(u,payload||{});if(a==='createSummary')return v2DocSummary_(u,payload||{});throw new Error('Tác vụ phát hành hồ sơ không hợp lệ.');}
