// SUNBOT School OS V2 — Document Release from locked Commercial Snapshot
// Official documents must originate from a locked Commercial Snapshot.
const V2_DOC_RELEASE=Object.freeze({
  SHEET:'DOCUMENTS',
  ROOT_NAME:'06_SCHOOL_OUTPUTS',
  SCHOOL_YEAR:'2026-2027',
  HEADERS:['document_id','school_id','commercial_snapshot_id','proposal_snapshot_id','document_type','document_name','template_code','template_id','version','status','folder_url','doc_url','pdf_url','created_by','created_at','updated_at'],
  TEMPLATES:[
    {code:'01',name:'Tờ trình đề nghị phê duyệt chủ trương triển khai Sunbot',template_id:'1R--yeWPEGTWNNUYvfpgK34lkRh4wK3MCPO7Sp2C9afQ',audience:'TRUONG',group:'CHU_TRUONG',release_state:'READY',customize:true},
    {code:'02',name:'Đề án mẫu triển khai chương trình Lập trình tư duy cùng Sunbot',template_id:'1PcQvOIefP2qrmiGlTDbw7mtL_1icQfaEj6qMIBhea54',audience:'TRUONG',group:'CHU_TRUONG',release_state:'READY',customize:true},
    {code:'03',name:'Thuyết minh mô hình Nhà trường làm chủ chương trình',template_id:'16PlSR_z3bRgQvLRL47VZzyMUeUU0RMkGFrwrBlYXkgg',audience:'TRUONG',group:'MO_HINH',release_state:'READY',customize:true},
    {code:'04',name:'Hồ sơ chương trình và ma trận mục tiêu giáo dục',template_id:'1br0P94TNHy1Mlxew5Ce6DwPFEhtGUifPpPDS-fHjQZM',audience:'TRUONG',group:'CHUONG_TRINH',release_state:'READY',customize:false},
    {code:'05',name:'Quy chuẩn kỹ thuật, cấu hình không gian và danh mục thiết bị',template_id:'1advcysF99Sj-LKExuezrYMO4R5yvqPfFd9P-myOrfIQ',audience:'TRUONG',group:'KY_THUAT',release_state:'READY',customize:true},
    {code:'06',name:'Hướng dẫn an toàn, bảo quản và sử dụng thiết bị',template_id:'1pHRkq4fIou2nN3cunaI1F2fX3eN-neJdX8Iytb_9gKM',audience:'TRUONG',group:'KY_THUAT',release_state:'READY',customize:false},
    {code:'07',name:'Hai phương án tài chính dành cho nhà trường',template_id:'1ubL2MSY5ycUh6PxmHMuhqLcERLpOy4vvidwa-aefwCQ',audience:'NOI_BO',group:'THUONG_MAI',release_state:'INTERNAL_ONLY',customize:true},
    {code:'08',name:'Kế hoạch đào tạo, sát hạch và phát triển đội ngũ',template_id:'1gJZK_xnbVF4qDTtg16iwrWWG-1_9LQVgWHtRTPhw7U0',audience:'TRUONG',group:'DAO_TAO',release_state:'READY',customize:true},
    {code:'09',name:'Kế hoạch vận hành và bảo đảm chất lượng',template_id:'1y6pDDlb7L2HF2X8F5FUF2NW7h2y-NiUXO1HqbXLWWQs',audience:'TRUONG',group:'VAN_HANH',release_state:'READY',customize:true},
    {code:'10',name:'Ma trận trách nhiệm giữa Nhà trường và Sunbot',template_id:'1en9wq-rIL4PxAZxQJ13aUH_U8gOpTJ-yTDRAH1SU31c',audience:'TRUONG',group:'VAN_HANH',release_state:'READY',customize:true},
    {code:'11',name:'Lộ trình triển khai, chỉ số đánh giá và cơ chế báo cáo',template_id:'1GtSa75o5zZL6RV1G6Ccm22Nr_Px6GT4bPpXPLlmn-LI',audience:'TRUONG',group:'VAN_HANH',release_state:'READY',customize:true},
    {code:'12',name:'Hồ sơ năng lực, pháp lý và các minh chứng của Kiro–Sunbot',template_id:'1q-9_HcbUCIZ2_xxHUHENVDWPlUryGe-o3L53I8kKFbk',audience:'NOI_BO',group:'MINH_CHUNG',release_state:'GATED_VERIFICATION',customize:false},
    {code:'13',name:'Bộ biểu mẫu triển khai cấp trường',template_id:'1Z9m7IVcpsO3BdB70efG2Q_fKAhP4sjSPYxO33M5fuLE',audience:'TRUONG',group:'BIEU_MAU',release_state:'READY',customize:true},
    {code:'14',name:'Bộ tài liệu thông tin và phối hợp với phụ huynh',template_id:'1ivLaMTrnBG-L1ixTQNonp9dK0ioyepFUqnZ-yiPJBP0',audience:'TRUONG_PH',group:'PHU_HUYNH',release_state:'READY',customize:true}
  ],
  PRESETS:[
    {code:'CHU_TRUONG',name:'Trình chủ trương',templates:['01','02','03','04','05','10','11']},
    {code:'KHOI_DONG',name:'Khởi động triển khai',templates:['04','05','06','08','09','10','11','13','14']},
    {code:'TRUONG_TU_DAY',name:'Trường tự tổ chức nhân sự',templates:['03','04','05','06','08','09','10','11','13','14']}
  ]
});
function v2DocRequireAdmin_(u){if(String(u.role_code||'').toUpperCase()!=='ADMIN')throw new Error('Chỉ Admin được phát hành hồ sơ.');}
function v2DocSheet_(){const ss=v2Db_();let sh=ss.getSheetByName(V2_DOC_RELEASE.SHEET);if(!sh){sh=ss.insertSheet(V2_DOC_RELEASE.SHEET);sh.getRange(1,1,1,V2_DOC_RELEASE.HEADERS.length).setValues([V2_DOC_RELEASE.HEADERS]);sh.setFrozenRows(1);return sh;}let h=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getDisplayValues()[0].map(String);V2_DOC_RELEASE.HEADERS.forEach(function(x){if(h.indexOf(x)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(x);h.push(x);}});return sh;}
function v2DocRows_(){v2DocSheet_();return v2Rows_(V2_DOC_RELEASE.SHEET);}
function v2DocCommercial_(id){const r=v2CommercialRows_().find(function(x){return String(x.commercial_snapshot_id)===String(id);});if(!r)throw new Error('Không tìm thấy Commercial Snapshot.');if(String(r.status)!=='LOCKED')throw new Error('Chỉ Commercial Snapshot đã khóa mới được phát hành.');return r;}
function v2DocSchool_(schoolId){const r=v2Rows_(V2_OS.S.SCHOOLS).find(function(x){return String(x.school_id)===String(schoolId);});if(!r)throw new Error('Không tìm thấy hồ sơ trường.');return r;}
function v2DocSafeName_(s){return String(s||'').replace(/[\\/:*?"<>|#%{}]/g,' ').replace(/\s+/g,' ').trim().slice(0,120)||'TRUONG';}
function v2DocChild_(parent,name){const it=parent.getFoldersByName(name);return it.hasNext()?it.next():parent.createFolder(name);}
function v2DocFolder_(commercial){const root=DriveApp.getFolderById(PRODUCTION.ROOT_FOLDER_ID);const output=v2DocChild_(root,V2_DOC_RELEASE.ROOT_NAME);const school=v2DocChild_(output,v2DocSafeName_(commercial.school_name)+' · '+commercial.school_id);const year=v2DocChild_(school,V2_DOC_RELEASE.SCHOOL_YEAR);return v2DocChild_(year,'CS-'+String(commercial.version||1)+' · '+commercial.commercial_snapshot_id);}
function v2DocAppend_(u,c,type,name,folder,docUrl,pdfUrl,templateCode,templateId){const now=v2Now_(),id='VDOC-'+Utilities.getUuid().slice(0,8).toUpperCase();v2Append_(V2_DOC_RELEASE.SHEET,{document_id:id,school_id:c.school_id,commercial_snapshot_id:c.commercial_snapshot_id,proposal_snapshot_id:c.proposal_snapshot_id,document_type:type,document_name:name,template_code:templateCode||'',template_id:templateId||'',version:String(c.version||1),status:'READY',folder_url:folder.getUrl(),doc_url:docUrl||'',pdf_url:pdfUrl||'',created_by:u.user_id,created_at:now,updated_at:now});v2Audit_('DOCUMENT',id,'CREATE','commercial_snapshot_id','',c.commercial_snapshot_id,u.user_id);return id;}
function v2DocList_(u,p){v2DocRequireAdmin_(u);p=p||{};return v2DocRows_().filter(function(r){return !p.commercial_snapshot_id||String(r.commercial_snapshot_id)===String(p.commercial_snapshot_id);}).sort(function(a,b){return String(b.created_at||'').localeCompare(String(a.created_at||''));}).map(function(r){return {document_id:r.document_id,school_id:r.school_id,commercial_snapshot_id:r.commercial_snapshot_id,proposal_snapshot_id:r.proposal_snapshot_id,document_type:r.document_type,document_name:r.document_name,template_code:r.template_code||'',template_id:r.template_id||'',version:r.version,status:r.status,folder_url:r.folder_url,doc_url:r.doc_url,pdf_url:r.pdf_url,created_by:r.created_by,created_at:r.created_at};});}
function v2DocPrepare_(u,p){v2DocRequireAdmin_(u);const c=v2DocCommercial_(String((p||{}).commercial_snapshot_id||'')),folder=v2DocFolder_(c);return {ok:true,commercial_snapshot_id:c.commercial_snapshot_id,school_id:c.school_id,school_name:c.school_name,folder_url:folder.getUrl(),school_year:V2_DOC_RELEASE.SCHOOL_YEAR};}
function v2DocRegistry_(u){v2DocRequireAdmin_(u);return {templates:V2_DOC_RELEASE.TEMPLATES.map(function(t){return {code:t.code,name:t.name,audience:t.audience,group:t.group,release_state:t.release_state,customize:!!t.customize,selectable:t.release_state==='READY'};}),presets:V2_DOC_RELEASE.PRESETS,school_year:V2_DOC_RELEASE.SCHOOL_YEAR};}
function v2DocTokenMap_(c,school){return {'{{TEN_TRUONG}}':c.school_name||school.school_name||'','{{SCHOOL_NAME}}':c.school_name||school.school_name||'','{{SCHOOL_ID}}':c.school_id||'','{{COMMERCIAL_SNAPSHOT_ID}}':c.commercial_snapshot_id||'','{{PHIEN_BAN}}':String(c.version||1),'{{VERSION}}':String(c.version||1),'{{NAM_HOC}}':V2_DOC_RELEASE.SCHOOL_YEAR,'{{SCHOOL_YEAR}}':V2_DOC_RELEASE.SCHOOL_YEAR,'{{PRICEBOOK_VERSION}}':c.pricebook_version||'','{{TINH_THANH}}':school.province||'','{{QUAN_HUYEN}}':school.district||'','{{DIA_CHI}}':school.address||'','{{DAU_MOI}}':school.contact_name||'','{{VAI_TRO_DAU_MOI}}':school.contact_role||''};}
function v2DocReplaceTokens_(docId,map){try{const doc=DocumentApp.openById(docId),body=doc.getBody();Object.keys(map).forEach(function(k){const pattern=k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');body.replaceText(pattern,String(map[k]||''));});doc.saveAndClose();}catch(e){throw new Error('Không thể cá thể hóa template: '+e.message);}}
function v2DocTemplateByCode_(code){return V2_DOC_RELEASE.TEMPLATES.find(function(t){return String(t.code)===String(code);});}
function v2DocGenerateTemplate_(u,c,school,folder,t){if(!t)throw new Error('Template không tồn tại.');if(t.release_state!=='READY')throw new Error('Tài liệu '+t.code+' chưa được phép phát hành từ hệ thống.');const existing=v2DocRows_().find(function(r){return String(r.commercial_snapshot_id)===String(c.commercial_snapshot_id)&&String(r.template_code)===String(t.code)&&String(r.status)==='READY';});if(existing)return {code:t.code,name:t.name,reused:true,document_id:existing.document_id,doc_url:existing.doc_url,pdf_url:existing.pdf_url,folder_url:existing.folder_url};let master;try{master=DriveApp.getFileById(t.template_id);}catch(e){throw new Error('Không truy cập được master '+t.code+'.');}const prefix=t.code+' · '+v2DocSafeName_(t.name),fileName=prefix+' · '+v2DocSafeName_(c.school_name)+' · v'+String(c.version||1);const copy=master.makeCopy(fileName,folder);v2DocReplaceTokens_(copy.getId(),v2DocTokenMap_(c,school));const pdf=folder.createFile(copy.getAs(MimeType.PDF).setName(fileName+'.pdf'));const id=v2DocAppend_(u,c,'TEMPLATE_'+t.code,t.code+'. '+t.name,folder,copy.getUrl(),pdf.getUrl(),t.code,t.template_id);return {code:t.code,name:t.name,reused:false,document_id:id,doc_url:copy.getUrl(),pdf_url:pdf.getUrl(),folder_url:folder.getUrl()};}
function v2DocGenerateBatch_(u,p){v2DocRequireAdmin_(u);p=p||{};const c=v2DocCommercial_(String(p.commercial_snapshot_id||'')),school=v2DocSchool_(c.school_id),folder=v2DocFolder_(c);let codes=Array.isArray(p.template_codes)?p.template_codes.map(String):[];if(p.preset_code){const preset=V2_DOC_RELEASE.PRESETS.find(function(x){return x.code===String(p.preset_code);});if(!preset)throw new Error('Gói hồ sơ không tồn tại.');codes=preset.templates.slice();}codes=Array.from(new Set(codes)).filter(Boolean);if(!codes.length)throw new Error('Chưa chọn tài liệu cần tạo.');if(codes.length>12)throw new Error('Mỗi lần chỉ tạo tối đa 12 tài liệu.');const out=[];codes.forEach(function(code){out.push(v2DocGenerateTemplate_(u,c,school,folder,v2DocTemplateByCode_(code)));});v2Audit_('COMMERCIAL_SNAPSHOT',c.commercial_snapshot_id,'GENERATE_DOCUMENT_BATCH','template_codes','',codes.join(','),u.user_id);return {ok:true,commercial_snapshot_id:c.commercial_snapshot_id,folder_url:folder.getUrl(),documents:out};}
function v2DocSummary_(u,p){v2DocRequireAdmin_(u);const c=v2DocCommercial_(String((p||{}).commercial_snapshot_id||''));const existing=v2DocRows_().find(function(r){return String(r.commercial_snapshot_id)===String(c.commercial_snapshot_id)&&String(r.document_type)==='PLAN_SUMMARY'&&String(r.status)==='READY';});if(existing)return {ok:true,reused:true,document_id:existing.document_id,doc_url:existing.doc_url,pdf_url:existing.pdf_url,folder_url:existing.folder_url};const school=v2DocSchool_(c.school_id),folder=v2DocFolder_(c),ref='SB-PA-'+Utilities.formatDate(new Date(),'Asia/Ho_Chi_Minh','yyyyMMdd')+'-'+Utilities.getUuid().slice(0,5).toUpperCase(),title='TÓM TẮT PHƯƠNG ÁN SUNBOT – '+c.school_name;const doc=DocumentApp.create(title),body=doc.getBody();body.appendParagraph('SUNBOT · KIRO VIỆT NAM').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('TÓM TẮT PHƯƠNG ÁN').setHeading(DocumentApp.ParagraphHeading.TITLE);const meta=body.appendTable([['Nhà trường',String(c.school_name||'')],['Mã phương án',String(c.commercial_snapshot_id)],['Phiên bản',String(c.version||1)],['Bảng giá',String(c.pricebook_version||'')],['Ngày khóa',String(c.locked_at||'').slice(0,10)]]);meta.setBorderWidth(0.5);body.appendHorizontalRule();body.appendParagraph('Phương án đã chốt').setHeading(DocumentApp.ParagraphHeading.HEADING2);String(c.summary_text||'Chưa có nội dung tóm tắt.').split('\n').filter(Boolean).forEach(function(line){body.appendParagraph(line);});body.appendParagraph('Thông tin trường').setHeading(DocumentApp.ParagraphHeading.HEADING2);body.appendParagraph('Loại hình: '+String(school.school_type||'')+'\nĐịa bàn: '+[school.district,school.province].filter(Boolean).join(', ')+'\nĐầu mối: '+String(school.contact_name||'')+(school.contact_role?' · '+school.contact_role:''));body.appendParagraph('Tài liệu được sinh từ Commercial Snapshot đã khóa. Mọi thay đổi thương mại cần tạo phiên bản Commercial Snapshot mới.').setItalic(true);doc.saveAndClose();const f=DriveApp.getFileById(doc.getId());f.setName(ref+' · Tóm tắt phương án · '+v2DocSafeName_(c.school_name));f.moveTo(folder);const pdf=folder.createFile(f.getAs(MimeType.PDF).setName(ref+' · Tóm tắt phương án · '+v2DocSafeName_(c.school_name)+'.pdf'));const id=v2DocAppend_(u,c,'PLAN_SUMMARY','Tóm tắt phương án',folder,f.getUrl(),pdf.getUrl(),'','');return {ok:true,reused:false,document_id:id,doc_url:f.getUrl(),pdf_url:pdf.getUrl(),folder_url:folder.getUrl(),reference:ref};}
function apiSessionV2Documents(sessionToken,action,payload){const u=v2RequireSession_(sessionToken),a=String(action||'');if(a==='list')return v2DocList_(u,payload||{});if(a==='registry')return v2DocRegistry_(u);if(a==='prepare')return v2DocPrepare_(u,payload||{});if(a==='createSummary')return v2DocSummary_(u,payload||{});if(a==='generateBatch')return v2DocGenerateBatch_(u,payload||{});throw new Error('Tác vụ phát hành hồ sơ không hợp lệ.');}
