// SUNBOT School OS V2 — V29 document data mapping & release preflight.
// Maps locked Commercial Snapshot + School OS + explicit Admin confirmations into 01–14 masters.
const V2_DOC_MAPPING=Object.freeze({
  VERSION:'2026.09.13-v29',
  ADMIN_FIELDS:{
    representative:{label:'Người đại diện + chức vụ'},
    approval_authority:{label:'Cơ quan/người có thẩm quyền'},
    age_group:{label:'Nhóm tuổi'},
    funding_source:{label:'Nguồn kinh phí / cơ chế được phê duyệt'},
    deployment_period:{label:'Thời gian dự kiến triển khai'},
    academic_contact:{label:'Đầu mối chuyên môn'},
    finance_contact:{label:'Đầu mối hành chính – tài chính'},
    space:{label:'Không gian triển khai'},
    management_authority:{label:'Cơ quan quản lý/địa phương'},
    related_units:{label:'Các đơn vị liên quan'},
    archive_unit:{label:'Bộ phận lưu hồ sơ'},
    signatory_title:{label:'Chức vụ người ký'}
  },
  RULES:{
    '01':{required:['representative','approval_authority','age_group','funding_source','deployment_period'],optional:['related_units','archive_unit','signatory_title']},
    '02':{required:['representative','academic_contact','finance_contact','age_group','space','management_authority','approval_authority'],optional:[]},
    '03':{required:[],optional:[]},'04':{required:[],optional:[]},'05':{required:[],optional:[]},'06':{required:[],optional:[]},
    '07':{required:[],optional:[]},'08':{required:[],optional:[]},'09':{required:[],optional:[]},'10':{required:[],optional:[]},
    '11':{required:[],optional:[]},'12':{required:[],optional:[]},'13':{required:[],optional:[]},'14':{required:[],optional:[]}
  }
});
function v2MapSnapshot_(c){let s={};try{s=JSON.parse(String(c.snapshot_json||'{}'));}catch(e){}const controls=s.controls||{},g=s.globals||{};function cv(id,f){const x=controls[id];if(!x)return f;const v=x.value===undefined?f:x.value;return v;}function num(id,f){const n=Number(cv(id,f));return isFinite(n)?n:f;}const children=num('children',0),classSize=num('classSize',20),manual=Math.round(num('classCountInput',0)),classes=manual>0?manual:(children?Math.ceil(children/Math.max(1,classSize)):0),points=Math.max(1,Math.round(num('campusCount',1))),lessons=Math.round(num('lessons',0)),months=Math.round(num('months',0)),trainTeachers=Math.round(num('trainingTeacherCount',0)),assessTeachers=Math.round(num('teacherCount',0)),programs=Number(g.programs||1)||1,term=Number(g.term||0)||0,mode=String(g.mode||'');let investment='';if(mode==='own')investment='Nhà trường đầu tư thiết bị';else if(mode==='provide')investment='Sunbot bố trí vốn thiết bị'+(term?' theo kỳ hạn '+term+' tháng':'');else if(mode)investment=mode;return {children:children,class_size:classSize,classes:classes,sites:points,lessons:lessons,months:months,training_teachers:trainTeachers,assessment_teachers:assessTeachers,programs:programs,term:term,mode:mode,investment:investment,launch:String(g.launch||''),rollout_funding:String(g.rolloutFunding||''),schema_version:s.schema_version||''};}
function v2MapCodes_(p){let codes=Array.isArray((p||{}).template_codes)?p.template_codes.map(String):[];if((p||{}).preset_code){const preset=V2_DOC_RELEASE.PRESETS.find(function(x){return x.code===String(p.preset_code);});if(!preset)throw new Error('Gói hồ sơ không tồn tại.');codes=preset.templates.slice();}return Array.from(new Set(codes)).filter(Boolean);}
function v2MapRequired_(codes){const out=[];codes.forEach(function(code){const r=V2_DOC_MAPPING.RULES[code]||{required:[]};(r.required||[]).forEach(function(k){if(out.indexOf(k)<0)out.push(k);});});return out;}
function v2MapAdminValues_(p){const src=(p&&p.admin_fields)||{},out={};Object.keys(V2_DOC_MAPPING.ADMIN_FIELDS).forEach(function(k){out[k]=v2Clean_(src[k],500);});return out;}
function v2MapAuto_(c,school){const x=v2MapSnapshot_(c);return {school_name:c.school_name||school.school_name||'',school_id:c.school_id||'',school_year:V2_DOC_RELEASE.SCHOOL_YEAR,address:school.address||'',province:school.province||'',district:school.district||'',children:x.children,classes:x.classes,sites:x.sites,lessons:x.lessons,months:x.months,programs:x.programs,training_teachers:x.training_teachers,assessment_teachers:x.assessment_teachers,investment:x.investment,term:x.term,pricebook_version:c.pricebook_version||'',commercial_snapshot_id:c.commercial_snapshot_id||'',version:String(c.version||1)};}
function v2MapPreflight_(u,p){v2DocRequireAdmin_(u);p=p||{};const c=v2DocCommercial_(String(p.commercial_snapshot_id||'')),school=v2DocSchool_(c.school_id),codes=v2MapCodes_(p),admin=v2MapAdminValues_(p),required=v2MapRequired_(codes),missing=required.filter(function(k){return !String(admin[k]||'').trim();}),auto=v2MapAuto_(c,school);if(!codes.length)throw new Error('Chưa chọn tài liệu.');return {ok:true,ready:missing.length===0,commercial_snapshot_id:c.commercial_snapshot_id,template_codes:codes,auto:auto,admin_fields:admin,required_fields:required.map(function(k){return {key:k,label:V2_DOC_MAPPING.ADMIN_FIELDS[k].label,value:admin[k]||''};}),missing:missing.map(function(k){return {key:k,label:V2_DOC_MAPPING.ADMIN_FIELDS[k].label};}),mapping_version:V2_DOC_MAPPING.VERSION};}
function v2MapReplace_(body,pattern,value){body.replaceText(pattern,String(value===undefined||value===null?'':value));}
function v2MapApply_(docId,c,school,admin){const a=v2MapAuto_(c,school),doc=DocumentApp.openById(docId),body=doc.getBody();const pairs={
  '\\[TÊN TRƯỜNG\\]':a.school_name,'\\[20…–20…\\]':a.school_year,'\\[ĐỊA CHỈ\\]':a.address,'\\[SỐ TRẺ\\]':a.children||'','\\[SỐ LỚP\\]':a.classes||'','\\[SỐ ĐIỂM TRƯỜNG\\]':a.sites||'','\\[4/6/8\\]':a.lessons||'','\\[SỐ THÁNG\\]':a.months||'','\\[NHÓM TUỔI\\]':admin.age_group||'','\\[TỪ THÁNG/NĂM ĐẾN THÁNG/NĂM\\]':admin.deployment_period||'','\\[TÊN CƠ QUAN/NGƯỜI CÓ THẨM QUYỀN\\]':admin.approval_authority||'','\\[CƠ QUAN/NGƯỜI CÓ THẨM QUYỀN\\]':admin.approval_authority||'','\\[CƠ QUAN QUẢN LÝ/ĐỊA PHƯƠNG\\]':admin.management_authority||'','\\[GHI RÕ NGUỒN DỰ KIẾN VÀ CƠ CHẾ ĐƯỢC PHÊ DUYỆT\\]':admin.funding_source||'','\\[CÁC ĐƠN VỊ LIÊN QUAN\\]':admin.related_units||'','\\[BỘ PHẬN\\]':admin.archive_unit||'','\\[CHỨC VỤ\\]':admin.signatory_title||'',
  '\\[Nhà trường đầu tư thiết bị/Sunbot bố trí vốn thiết bị theo kỳ hạn 24 hoặc 36 tháng theo phương án được phê duyệt\\]':a.investment||'','\\[NHÀ TRƯỜNG ĐẦU TƯ/SUNBOT BỐ TRÍ VỐN THIẾT BỊ THEO KỲ HẠN 24 HOẶC 36 THÁNG\\]':a.investment||'','\\[PHÒNG CHỨC NĂNG/PHÒNG HỌC/KHU VỰC ĐƯỢC KHẢO SÁT\\]':admin.space||''};Object.keys(pairs).forEach(function(k){v2MapReplace_(body,k,pairs[k]);});
  // Context-specific replacement for the repeated [HỌ TÊN – CHỨC VỤ] placeholder in Master 02.
  v2MapReplace_(body,'Người đại diện: \\[HỌ TÊN – CHỨC VỤ\\]','Người đại diện: '+(admin.representative||''));
  v2MapReplace_(body,'Đầu mối chuyên môn: \\[HỌ TÊN – CHỨC VỤ\\]','Đầu mối chuyên môn: '+(admin.academic_contact||''));
  v2MapReplace_(body,'Đầu mối hành chính – tài chính: \\[HỌ TÊN – CHỨC VỤ\\]','Đầu mối hành chính – tài chính: '+(admin.finance_contact||''));
  v2MapReplace_(body,'\\[HỌ VÀ TÊN – CHỨC VỤ\\]',admin.representative||'');
  // Curly canonical tokens remain supported for future-normalized masters.
  const curly={'\\{\\{TEN_TRUONG\\}\\}':a.school_name,'\\{\\{NAM_HOC\\}\\}':a.school_year,'\\{\\{DIA_CHI\\}\\}':a.address,'\\{\\{SO_TRE\\}\\}':a.children||'','\\{\\{SO_LOP\\}\\}':a.classes||'','\\{\\{SO_DIEM_TRUONG\\}\\}':a.sites||'','\\{\\{CUONG_DO\\}\\}':a.lessons||'','\\{\\{SO_THANG\\}\\}':a.months||'','\\{\\{PHUONG_AN_DAU_TU\\}\\}':a.investment||'','\\{\\{NGUOI_DAI_DIEN\\}\\}':admin.representative||'','\\{\\{CO_QUAN_PHE_DUYET\\}\\}':admin.approval_authority||'','\\{\\{NHOM_TUOI\\}\\}':admin.age_group||'','\\{\\{NGUON_KINH_PHI\\}\\}':admin.funding_source||''};Object.keys(curly).forEach(function(k){v2MapReplace_(body,k,curly[k]);});doc.saveAndClose();}
function v2MapUnresolved_(docId){const text=DocumentApp.openById(docId).getBody().getText(),m=text.match(/\[[^\]\n]{2,120}\]/g)||[];return Array.from(new Set(m)).slice(0,30);}
function v2MapGenerateOne_(u,c,school,folder,t,admin){if(!t||t.release_state!=='READY')throw new Error('Tài liệu chưa được phép phát hành.');const existing=v2DocRows_().find(function(r){return String(r.commercial_snapshot_id)===String(c.commercial_snapshot_id)&&String(r.template_code)===String(t.code)&&String(r.status)==='READY';});if(existing)return {code:t.code,name:t.name,reused:true,document_id:existing.document_id,doc_url:existing.doc_url,pdf_url:existing.pdf_url,folder_url:existing.folder_url};const master=DriveApp.getFileById(t.template_id),fileName=t.code+' · '+v2DocSafeName_(t.name)+' · '+v2DocSafeName_(c.school_name)+' · v'+String(c.version||1),copy=master.makeCopy(fileName,folder);try{v2MapApply_(copy.getId(),c,school,admin);const unresolved=v2MapUnresolved_(copy.getId());if(unresolved.length){copy.setName('CHƯA PHÁT HÀNH · '+fileName);throw new Error('Tài liệu '+t.code+' còn trường chưa xác nhận: '+unresolved.join(', '));}const pdf=folder.createFile(copy.getAs(MimeType.PDF).setName(fileName+'.pdf')),id=v2DocAppend_(u,c,'TEMPLATE_'+t.code,t.code+'. '+t.name,folder,copy.getUrl(),pdf.getUrl(),t.code,t.template_id);v2Audit_('DOCUMENT',id,'MAPPING',V2_DOC_MAPPING.VERSION,'',JSON.stringify({school_os:true,commercial_snapshot:true,admin_confirmed:Object.keys(admin).filter(function(k){return !!admin[k];})}),u.user_id);return {code:t.code,name:t.name,reused:false,document_id:id,doc_url:copy.getUrl(),pdf_url:pdf.getUrl(),folder_url:folder.getUrl()};}catch(e){throw e;}}
function v2MapGenerate_(u,p){const check=v2MapPreflight_(u,p);if(!check.ready)throw new Error('Cần xác nhận: '+check.missing.map(function(x){return x.label;}).join(', '));const c=v2DocCommercial_(check.commercial_snapshot_id),school=v2DocSchool_(c.school_id),folder=v2DocFolder_(c),admin=v2MapAdminValues_(p),out=[];check.template_codes.forEach(function(code){out.push(v2MapGenerateOne_(u,c,school,folder,v2DocTemplateByCode_(code),admin));});v2Audit_('COMMERCIAL_SNAPSHOT',c.commercial_snapshot_id,'GENERATE_MAPPED_DOCUMENT_BATCH','mapping_version','',V2_DOC_MAPPING.VERSION,u.user_id);return {ok:true,commercial_snapshot_id:c.commercial_snapshot_id,folder_url:folder.getUrl(),documents:out,mapping_version:V2_DOC_MAPPING.VERSION};}
function apiSessionV2DocMapping(sessionToken,action,payload){const u=v2RequireSession_(sessionToken),a=String(action||'');if(a==='preflight')return v2MapPreflight_(u,payload||{});if(a==='generate')return v2MapGenerate_(u,payload||{});throw new Error('Tác vụ mapping hồ sơ không hợp lệ.');}
